Repository ansible/molecule, pull requests merged in 2018-04, with the labels that each got.

#1224 Fixing functional tests
  .gitignore
  test/conftest.py
  test/functional/test_command.py
  test/scenarios/dependency/molecule/gilt/gilt.yml
  test/scenarios/plugins/molecule/default/gilt.yml
Labels: v2.12

#1225 Ensure prune properly removes empty dirs
  molecule/command/base.py
  test/unit/command/test_base.py
Labels: v2.12

#1226 Moved molecule_instance_config to host inventory
  molecule/provisioner/ansible.py
  test/unit/provisioner/test_ansible.py
Labels: breaking-change

#1227 Disable pytest caching plugin
  .gitignore
  molecule/verifier/testinfra.py
  test/unit/verifier/test_testinfra.py
Labels: v2.12

#1239 Bumped Ansible 2.4 minor version
  tox.ini
Labels: v2.13

#1246 Correct Docker container terminal sizing
  molecule/command/login.py
  molecule/driver/docker.py
  test/unit/driver/test_docker.py
Labels: v2.13

#1247 Delegated driver should report unknown on list
  molecule/driver/base.py
  molecule/driver/delegated.py
  test/functional/test_command.py
  test/unit/command/test_list.py
  test/unit/driver/test_azure.py
  test/unit/driver/test_delegated.py
  test/unit/driver/test_docker.py
  test/unit/driver/test_ec2.py
  test/unit/driver/test_gce.py
  test/unit/driver/test_lxc.py
  test/unit/driver/test_lxd.py
  test/unit/driver/test_openstack.py
  test/unit/driver/test_vagrant.py
Labels: v2.13

#1249 Retry downloading goss 3 times
  molecule/cookiecutter/scenario/verifier/goss/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/verify.yml
Labels: v2.13

#1251 Log vagrant errors
  molecule/provisioner/ansible/plugins/libraries/molecule_vagrant.py
Labels: v2.13

#1254 Disallow null provider.env values
  molecule/model/schema_v2.py
  test/unit/model/v2/test_provisioner_section.py
Labels: v2.13

#1255 Render inventory links relative to scenario dir
  molecule/provisioner/ansible.py
  test/scenarios/host_group_vars/group_vars/example/all.yml
  test/scenarios/host_group_vars/host_vars/instance/all.yml
  test/scenarios/host_group_vars/molecule/links/molecule.yml
  test/scenarios/host_group_vars/molecule/links/playbook.yml
  test/scenarios/host_group_vars/molecule/links/prepare.yml
  test/unit/provisioner/test_ansible.py
Labels: breaking-change, v2.13

#1256 Converge with built in Molecule skip tags
  molecule/provisioner/ansible.py
  test/unit/provisioner/test_ansible.py
  test/unit/provisioner/test_ansible_playbook.py
Labels: v2.13

#1258 Support Void Linux when using Docker driver.
  molecule/cookiecutter/scenario/driver/docker/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/Dockerfile.j2
  test/resources/playbooks/docker/Dockerfile.j2
Labels: v2.13

#1264 Minor fixes to Goss verifier playbook
  test/scenarios/verifier/molecule/goss/verify.yml
  test/scenarios/verifier/molecule/inspec/verify.yml
Labels: v2.13

#1261 Update documentation for verify and idempotency checks
  molecule/command/idempotence.py
Labels: v2.13

#1268 Bumped testinfra version
  requirements.txt
  tox.ini
Labels: v2.13

#1235 Add parameter for vagrant provider override
  molecule/provisioner/ansible/plugins/libraries/molecule_vagrant.py
Labels: v2.13

#1238 add docker_host attribute to templates to allow talking to a remote n…
  molecule/cookiecutter/scenario/driver/docker/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/docker/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/driver/docker.py
Labels: v2.13
