Repository ansible/molecule, pull requests merged in 2018-11, with the labels that each got.

#1531 Molecule - Ansible by Red Hat
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/security_bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dco.yml
  CONTRIBUTING.rst
  DCO_1_1.md
  LICENSE
  README.rst
  build/Dockerfile
  build/Makefile
  doc/source/conf.py
  doc/source/development.rst
  doc/source/examples.rst
  molecule/provisioner/lint/ansible_lint.py
  setup.cfg
  test/scenarios/idempotence/tasks/main.yml
Labels: docs, enhancement, important-change

#1536 Tidy up more docs
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGELOG.rst
  README.rst
  doc/source/development.rst
  doc/source/installation.rst
Labels: docs

#1537 Fix RST issue in CHANGELOG.rst
  CHANGELOG.rst
Labels: docs

#1562 Packaging: improve distribution metadata
  setup.cfg
Labels: bug, enhancement

#1560 Fix test side-effect of not returning 🔙 from chdir
  test/conftest.py
  test/functional/conftest.py
  test/functional/docker/test_scenarios.py
Labels: bug

#1559 Improve pytest config
  pytest.ini
  tox.ini
Labels: enhancement

#1557 Improve tox config
  tox.ini
Labels: enhancement

#1565 Drop unused import from test.conftest
  test/conftest.py
Labels: bug

#1564 Fix doc env in tox
  tox.ini
Labels: bug, docs

#1545 Add ability to call molecule as a python module
  CHANGELOG.rst
  doc/source/installation.rst
  molecule/__main__.py
Labels: docs

#1530 Bump ansible-lint to 3.5.1
  requirements.txt
Labels: bug, enhancement

#1586 Shard nightly jobs in Travis CI
  .travis.yml
Labels: bug

#1590 Switch Travis CI to use VMs instead of containers infra
  .travis.yml
Labels: enhancement
