Repository ansible/molecule, pull requests merged in 2018-02, with the labels that each got.

#1119 Improved quickstart video
  README.rst
Labels: v2.8

#1120 Using raw html to set image width
  README.rst
Labels: v2.8

#1123 Corrected ansible args
  molecule/provisioner/ansible_playbook.py
  test/unit/provisioner/test_ansible_playbook.py
Labels: bug, v2.8

#1125 Validate schema for invalid ansible config options
  molecule/model/base.py
  molecule/model/schema.py
  molecule/model/schema_v1.py
  test/unit/conftest.py
  test/unit/model/test_schema.py
Labels: v2.9

#1126 Disallow privilege_escalation via schema
  molecule/model/base.py
  molecule/model/schema.py
  molecule/provisioner/ansible.py
  test/unit/model/test_schema.py
  test/unit/provisioner/test_ansible.py
Labels: v2.9

#1128 Corrected ability to set multiple x options
  molecule/provisioner/lint/ansible_lint.py
  test/unit/model/test_schema.py
  test/unit/provisioner/lint/test_ansible_lint.py
Labels: v2.9

#1131 Ignore psutil on cygwin platform
  requirements.txt
Labels: v2.9

#1135 Fix confusion between exposed and published ports in docker create playbook
  molecule/cookiecutter/scenario/driver/docker/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/driver/docker.py
  test/resources/playbooks/docker/create.yml
Labels: v2.9

#1118 Adding provision option for Vagrant provider
  doc/source/configuration.rst
  molecule/cookiecutter/scenario/driver/vagrant/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/provisioner/ansible/plugins/libraries/molecule_vagrant.py
  test/resources/playbooks/vagrant/create.yml
  test/scenarios/driver/vagrant/molecule/default/molecule.yml
Labels: v2.9

#1147 Reduce create time with vagrant
  molecule/provisioner/ansible/plugins/libraries/molecule_vagrant.py
Labels: v2.9

#1148 Namespaced Docker registry
  molecule/cookiecutter/scenario/driver/docker/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/Dockerfile.j2
  molecule/driver/docker.py
  test/resources/playbooks/docker/Dockerfile.j2
Labels: breaking-change, v2.9

#1146 Replace >>> with $ for documentation
  molecule/command/check.py
  molecule/command/converge.py
  molecule/command/create.py
  molecule/command/dependency.py
  molecule/command/destroy.py
  molecule/command/idempotence.py
  molecule/command/init/role.py
  molecule/command/init/scenario.py
  molecule/command/init/template.py
  molecule/command/lint.py
  molecule/command/list.py
  molecule/command/login.py
  molecule/command/prepare.py
  molecule/command/side_effect.py
  molecule/command/syntax.py
  molecule/command/test.py
  molecule/command/verify.py
Labels: v2.9

#1156 Bumped yamllint version
  requirements.txt
Labels: v2.9
