Repository ansible/molecule, pull requests merged in 2018-03, with the labels that each got.

#1163 Fix line length in cookie cutter README
  molecule/cookiecutter/role/{{cookiecutter.role_name}}/README.md
Labels: v2.10

#1168 Update molecule_vagrant.py
  molecule/provisioner/ansible/plugins/libraries/molecule_vagrant.py
Labels: v2.10

#1172 Allow Vagrant to automatically insert a keypair
  molecule/provisioner/ansible/plugins/libraries/molecule_vagrant.py
Labels: v2.10

#1173 Properly skipping Vagrant speedup keys in provider
  molecule/provisioner/ansible/plugins/libraries/molecule_vagrant.py
Labels: v2.10

#1175 Corrected synced_folders usage
  molecule/provisioner/ansible/plugins/libraries/molecule_vagrant.py
Labels: v2.10

#1176 Ability to log into a Docker registry
  molecule/cookiecutter/scenario/driver/docker/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/driver/docker.py
  test/resources/playbooks/docker/create.yml
Labels: v2.11

#1180 Vagrantfile cleanup
  .gitignore
  molecule/cookiecutter/scenario/driver/vagrant/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/driver/vagrant.py
  molecule/provisioner/ansible/plugins/libraries/molecule_vagrant.py
  test/resources/playbooks/vagrant/create.yml
  test/scenarios/driver/vagrant/molecule/multi-node/molecule.yml
  test/scenarios/driver/vagrant/molecule/multi-node/prepare.yml
  test/scenarios/driver/vagrant/molecule/multi-node/tests/test_instance-1.py
  test/scenarios/driver/vagrant/molecule/multi-node/tests/test_instance-2.py
Labels: important-change, v2.11

#1190 Move merge_dicts into util
  molecule/config.py
  molecule/dependency/ansible_galaxy.py
  molecule/dependency/base.py
  molecule/dependency/gilt.py
  molecule/dependency/shell.py
  molecule/driver/azure.py
  molecule/driver/ec2.py
  molecule/driver/gce.py
  molecule/driver/openstack.py
  molecule/driver/vagrant.py
  molecule/lint/base.py
  molecule/lint/yamllint.py
  molecule/provisioner/ansible.py
  molecule/provisioner/ansible/plugins/libraries/molecule_vagrant.py
  molecule/provisioner/ansible_playbook.py
  molecule/provisioner/lint/ansible_lint.py
  molecule/provisioner/lint/base.py
  molecule/util.py
  molecule/verifier/base.py
  molecule/verifier/goss.py
  molecule/verifier/lint/base.py
  molecule/verifier/lint/flake8.py
  molecule/verifier/testinfra.py
  test/unit/command/test_create.py
  test/unit/command/test_destroy.py
  test/unit/command/test_login.py
  test/unit/command/test_side_effect.py
  test/unit/conftest.py
  test/unit/dependency/test_ansible_galaxy.py
  test/unit/dependency/test_gilt.py
  test/unit/dependency/test_shell.py
  test/unit/driver/test_azure.py
  test/unit/driver/test_delegated.py
  test/unit/driver/test_docker.py
  test/unit/driver/test_ec2.py
  test/unit/driver/test_gce.py
  test/unit/driver/test_lxc.py
  test/unit/driver/test_lxd.py
  test/unit/driver/test_openstack.py
  test/unit/driver/test_vagrant.py
  test/unit/lint/test_yamllint.py
  test/unit/provisioner/lint/test_ansible_lint.py
  test/unit/provisioner/test_ansible.py
  test/unit/provisioner/test_ansible_playbooks.py
  test/unit/test_config.py
  test/unit/test_util.py
  test/unit/verifier/lint/test_flake8.py
  test/unit/verifier/test_goss.py
  test/unit/verifier/test_testinfra.py
Labels: v2.11

#1191 Bumped version of jinja2
  requirements.txt
Labels: v2.11

#1197 Bumped version of YAPF
  molecule/command/base.py
  molecule/command/init/base.py
  molecule/command/init/template.py
  molecule/command/lint.py
  molecule/provisioner/ansible.py
  molecule/verifier/lint/flake8.py
  test-requirements.txt
  test/functional/conftest.py
  test/unit/provisioner/test_ansible.py
Labels: v2.11

#1198 Capitalized initialisms in Ec2 Gce Lxc Lxd
  doc/source/configuration.rst
  molecule/config.py
  molecule/driver/ec2.py
  molecule/driver/gce.py
  molecule/driver/lxc.py
  molecule/driver/lxd.py
  test/unit/driver/test_ec2.py
  test/unit/driver/test_gce.py
  test/unit/driver/test_lxc.py
  test/unit/driver/test_lxd.py
  test/unit/test_config.py
Labels: v2.11

#1200 Correct verbose flag options with `--debug`
  molecule/dependency/ansible_galaxy.py
  molecule/provisioner/ansible.py
  molecule/util.py
  molecule/verifier/testinfra.py
  test/unit/dependency/test_ansible_galaxy.py
  test/unit/provisioner/test_ansible.py
  test/unit/test_util.py
  test/unit/verifier/test_testinfra.py
Labels: v2.11

#1206 Move Molecule playbook vars into host inventory
  molecule/cookiecutter/scenario/driver/azure/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/azure/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/delegated/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/delegated/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/docker/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/docker/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/ec2/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/ec2/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/gce/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/gce/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/lxc/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/lxc/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/lxd/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/lxd/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/openstack/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/openstack/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/vagrant/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/vagrant/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/provisioner/ansible.py
  test/resources/playbooks/azure/create.yml
  test/resources/playbooks/azure/destroy.yml
  test/resources/playbooks/docker/create.yml
  test/resources/playbooks/docker/destroy.yml
  test/resources/playbooks/ec2/create.yml
  test/resources/playbooks/ec2/destroy.yml
  test/resources/playbooks/gce/create.yml
  test/resources/playbooks/gce/destroy.yml
  test/resources/playbooks/lxc/create.yml
  test/resources/playbooks/lxc/destroy.yml
  test/resources/playbooks/lxd/create.yml
  test/resources/playbooks/lxd/destroy.yml
  test/resources/playbooks/openstack/create.yml
  test/resources/playbooks/openstack/destroy.yml
  test/resources/playbooks/vagrant/create.yml
  test/resources/playbooks/vagrant/destroy.yml
  test/unit/provisioner/test_ansible.py
Labels: v2.12

#1210 Added dind support and docs
  Dockerfile
  Makefile
  doc/source/examples.rst
Labels: v2.12

#1212 Relaxed schema validation
  molecule/model/schema_v2.py
  test/unit/model/v2/test_driver_section.py
Labels: v2.12

#1207 yamllint: exclude .venv directory
  molecule/lint/yamllint.py
Labels: v2.12

#1211 AnsibleLint: fix docstring
  molecule/provisioner/lint/ansible_lint.py
Labels: v2.12

#1215 Remove include tasks from driver playbooks
  molecule/cookiecutter/scenario/driver/azure/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/azure/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/keypair.yml
  molecule/cookiecutter/scenario/driver/azure/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/network.yml
  molecule/cookiecutter/scenario/driver/azure/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/resource_group.yml
  molecule/cookiecutter/scenario/driver/ec2/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/ec2/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/keypair.yml
  molecule/cookiecutter/scenario/driver/ec2/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/security_group.yml
  molecule/cookiecutter/scenario/driver/openstack/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/openstack/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/keypair.yml
  molecule/cookiecutter/scenario/driver/openstack/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/security_group.yml
  test/resources/playbooks/azure/create.yml
  test/resources/playbooks/azure/keypair.yml
  test/resources/playbooks/azure/network.yml
  test/resources/playbooks/azure/resource_group.yml
  test/resources/playbooks/ec2/create.yml
  test/resources/playbooks/ec2/keypair.yml
  test/resources/playbooks/ec2/security_group.yml
  test/resources/playbooks/openstack/create.yml
  test/resources/playbooks/openstack/keypair.yml
  test/resources/playbooks/openstack/neutron.yml
  test/resources/playbooks/openstack/security_group.yml
Labels: v2.12

#1216 Added and tested Ansible 2.5 support
  tox.ini
Labels: v2.12

#1217 Corrected yamllint
  .yamllint
  molecule/cookiecutter/scenario/driver/openstack/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  test/resources/playbooks/delegated/create/openstack.yml
  test/resources/playbooks/openstack/create.yml
  tox.ini
Labels: v2.12

#1218 Moved temporary files to $TMPDIR
  molecule/config.py
  molecule/provisioner/base.py
  molecule/scenario.py
  molecule/util.py
  molecule/verifier/base.py
  test/unit/test_config.py
  test/unit/test_scenario.py
  test/unit/test_state.py
Labels: important-change, v2.12

#1222 Added cookiecutter tests
  molecule/command/init/role.py
  molecule/command/init/scenario.py
  molecule/cookiecutter/molecule/cookiecutter.json
  molecule/cookiecutter/molecule/{{cookiecutter.role_name}}/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/molecule.yml
  test/conftest.py
  test/functional/conftest.py
  test/unit/cookiecutter/__init.py__
  test/unit/cookiecutter/test_molecule.py
Labels: v2.12

#1223 Allow verify playbook to be shared
  molecule/config.py
  molecule/cookiecutter/scenario/verifier/goss/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/verify.yml
  molecule/model/schema_v2.py
  molecule/provisioner/ansible.py
  molecule/provisioner/ansible_playbooks.py
  molecule/verifier/goss.py
  test/scenarios/verifier/molecule/goss/verify.yml
  test/unit/provisioner/test_ansible.py
  test/unit/provisioner/test_ansible_playbooks.py
  test/unit/verifier/test_goss.py
Labels: v2.12
