Repository ansible/molecule, pull requests merged in 2019-04, with the labels that each got.

#1870 Improve supports_* driver checks (use Ansible logic)
  test/functional/conftest.py
  test/resources/playbooks/docker/create.yml
  test/resources/playbooks/docker/destroy.yml
Labels: CI

#1876 Show systemd container without privileged mode or SYS_ADMIN capabilit…
  doc/source/examples.rst
Labels: docker-image, docs

#1736 Add digitalocean driver
  doc/source/configuration.rst
  molecule/config.py
  molecule/cookiecutter/molecule/{{cookiecutter.role_name}}/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/molecule.yml
  molecule/cookiecutter/scenario/driver/digitalocean/cookiecutter.json
  molecule/cookiecutter/scenario/driver/digitalocean/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/digitalocean/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/digitalocean/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/digitalocean/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/playbook.yml
  molecule/cookiecutter/scenario/driver/digitalocean/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/prepare.yml
  molecule/driver/digitalocean.py
  molecule/model/schema_v2.py
  setup.cfg
  test/functional/conftest.py
  test/functional/test_command.py
  test/resources/playbooks/digitalocean/create.yml
  test/resources/playbooks/digitalocean/destroy.yml
  test/scenarios/driver/digitalocean/molecule/default/molecule.yml
  test/scenarios/driver/digitalocean/molecule/default/playbook.yml
  test/scenarios/driver/digitalocean/molecule/default/tests/test_default.py
  test/scenarios/driver/digitalocean/molecule/multi-node/molecule.yml
  test/scenarios/driver/digitalocean/molecule/multi-node/playbook.yml
  test/scenarios/driver/digitalocean/molecule/multi-node/tests/test_default.py
  test/unit/cookiecutter/test_molecule.py
  test/unit/driver/test_digitalocean.py
  test/unit/model/v2/test_driver_section.py
  test/unit/test_config.py
Labels: enhancement

#1884 Enable image by owner and name
  molecule/cookiecutter/scenario/driver/ec2/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/driver/ec2.py
  test/resources/playbooks/ec2/create.yml
Labels: driver-ec2

#1739 Modify sequences to run dependency first
  CHANGELOG.rst
  molecule/command/base.py
  molecule/command/check.py
  molecule/command/cleanup.py
  molecule/command/converge.py
  molecule/command/create.py
  molecule/command/dependency.py
  molecule/command/destroy.py
  molecule/command/idempotence.py
  molecule/command/lint.py
  molecule/command/prepare.py
  molecule/command/side_effect.py
  molecule/command/syntax.py
  molecule/command/test.py
  molecule/command/verify.py
  molecule/config.py
  molecule/driver/azure.py
  molecule/driver/docker.py
  molecule/driver/ec2.py
  molecule/driver/gce.py
  molecule/driver/linode.py
  molecule/driver/lxc.py
  molecule/driver/lxd.py
  molecule/driver/openstack.py
  molecule/driver/vagrant.py
  molecule/scenario.py
  test/unit/command/test_base.py
  test/unit/command/test_destroy.py
  test/unit/test_scenario.py
  test/unit/test_scenarios.py
Labels: enhancement, important-change

#1882 Add driver sanity checks (only Docker for now ...)
  molecule/driver/azure.py
  molecule/driver/base.py
  molecule/driver/delegated.py
  molecule/driver/docker.py
  molecule/driver/ec2.py
  molecule/driver/gce.py
  molecule/driver/linode.py
  molecule/driver/lxc.py
  molecule/driver/lxd.py
  molecule/driver/openstack.py
  molecule/driver/vagrant.py
  molecule/provisioner/ansible_playbook.py
  molecule/state.py
  test/unit/driver/test_docker.py
Labels: enhancement

#1663 Add --molecule-idempotence-notest tag to skip-tags during idempotence…
  molecule/provisioner/ansible.py
  test/unit/provisioner/test_ansible_playbook.py
Labels: enhancement

#1653 add ansible_args to the ansible provisioner
  molecule/config.py
  molecule/provisioner/ansible.py
  molecule/provisioner/ansible_playbook.py
  test/unit/provisioner/test_ansible_playbook.py
Labels: enhancement

#1647 Add specification of a custom cookiecutter template for role creation
  molecule/command/init/base.py
  molecule/command/init/role.py
  molecule/command/init/scenario.py
  test/resources/custom_role_template/cookiecutter.json
  test/resources/custom_role_template/{{cookiecutter.role_name}}/README.md
  test/resources/invalid_role_template/bad_format/README.md
  test/resources/invalid_role_template/cookiecutter.json
  test/unit/command/init/test_role.py
Labels: enhancement

#1646 update goss verify.yml to allow to pass host to run on
  molecule/cookiecutter/scenario/verifier/goss/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/verify.yml
  molecule/verifier/goss.py
  test/scenarios/verifier/molecule/goss/molecule.yml
  test/scenarios/verifier/molecule/goss/tests/test_default.yml
  test/scenarios/verifier/molecule/goss/tests/test_host_instance1.yml
  test/scenarios/verifier/molecule/goss/tests/test_host_instance2.yml
  test/scenarios/verifier/molecule/goss/verify.yml
Labels: enhancement

#1914 Point to stable documentation in the README
  README.rst
Labels: docs

#1895 Change packaging toolkit to use setuptools-scm
  .git_archival.txt
  .gitattributes
  .travis.yml
  MANIFEST.in
  lint-requirements.txt
  molecule/__init__.py
  pyproject.toml
  requirements.txt
  setup.cfg
  setup.py
  test-requirements.txt
  tox.ini
Labels: enhancement

#1915 Pin yapf to <0.27 (0.26)
  tox.ini
Labels: CI

#1918 Remove flake8 excludes
  .flake8
  doc/source/conf.py
Labels: CI

#1960 Fail on warnings from setuptools dist meta
  setup.cfg
Labels: docs

#1961 Remove Python/Ansible manual version checks
  molecule/shell.py
  test/functional/conftest.py
Labels: CI

#1962 Fixed flake8 cause by outdated check
  test/functional/conftest.py
Labels: CI

#1965 Remove references to missing fixture
  test/functional/docker/test_scenarios.py
  test/functional/test_command.py
Labels: CI

#1967 Backported fix that prevented run with python 3.5
  test/functional/conftest.py
  test/functional/docker/test_scenarios.py
  test/functional/test_command.py
  tox.ini
Labels: critical

#1977 Fix the CI: remove comment that Tox cannot parse correctly
  tox.ini
Labels: CI

#1968 Update the installation assumptions doc
  doc/source/installation.rst
Labels: docs, enhancement, important-change, ux

#1993 Avoid failure to lint due to fstrings in docs
  tox.ini
Labels: bug

#1897 Adopt use of module invocation method for tools
  tox.ini
Labels: CI

#1919 Increase yamllint coverage
  .github/CODEOWNERS
  .github/dco.yml
  .readthedocs.yml
  .travis.yml
  .yamllint
  tox.ini
Labels: CI

#1995 Refactor tox envs
  tox.ini
Labels: CI, enhancement, ux

#2004 Drop sphinx make files
  doc/Makefile
  doc/make.bat
Labels: bug, docs

#1714 Add Ansible verifier
  molecule/command/init/role.py
  molecule/command/init/scenario.py
  molecule/config.py
  molecule/cookiecutter/scenario/verifier/ansible/cookiecutter.json
  molecule/cookiecutter/scenario/verifier/ansible/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/verify.yml
  molecule/model/schema_v2.py
  molecule/provisioner/lint/ansible_lint.py
  molecule/verifier/ansible.py
  molecule/verifier/base.py
  molecule/verifier/lint/ansible_lint.py
  test/functional/conftest.py
  test/functional/test_command.py
  test/scenarios/driver/docker/molecule/ansible-verifier/molecule.yml
  test/scenarios/driver/docker/molecule/ansible-verifier/playbook.yml
  test/scenarios/driver/docker/molecule/ansible-verifier/verify.yml
  test/unit/model/v2/test_verifier_section.py
  test/unit/test_config.py
  test/unit/verifier/lint/test_ansible_lint.py
  test/unit/verifier/test_ansible.py
Labels: docs, enhancement

#2019 Ensure that ip command is available in docker images
  molecule/cookiecutter/scenario/driver/docker/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/Dockerfile.j2
  test/resources/playbooks/docker/Dockerfile.j2
Labels: bug, docker
