Repository ansible/molecule, pull requests merged in 2019-07, with the labels that each got.

#2140 Parallelize unit test execution
  test/conftest.py
  test/unit/conftest.py
  tox.ini
Labels: CI

#2137 Add experimental ``--parallel`` functionality
  CHANGELOG.rst
  docs/examples.rst
  docs/faq.rst
  molecule/command/base.py
  molecule/command/check.py
  molecule/command/destroy.py
  molecule/command/test.py
  molecule/config.py
  molecule/platforms.py
  molecule/provisioner/ansible/plugins/filters/molecule_core.py
  molecule/scenario.py
  molecule/state.py
  molecule/util.py
  test/unit/test_config.py
Labels: enhancement, important-change

#2146 Only test default driver with delegated
  test/functional/test_command.py
Labels: CI

#2151 Remove old delegated driver tests
  test/scenarios/driver/delegated/molecule/ec2/molecule.yml
  test/scenarios/driver/delegated/molecule/ec2/playbook.yml
  test/scenarios/driver/delegated/molecule/ec2/prepare.yml
  test/scenarios/driver/delegated/molecule/ec2/tests/test_default.py
  test/scenarios/driver/delegated/molecule/gce/molecule.yml
  test/scenarios/driver/delegated/molecule/gce/playbook.yml
  test/scenarios/driver/delegated/molecule/gce/tests/test_default.py
  test/scenarios/driver/delegated/molecule/openstack/molecule.yml
  test/scenarios/driver/delegated/molecule/openstack/playbook.yml
  test/scenarios/driver/delegated/molecule/openstack/prepare.yml
  test/scenarios/driver/delegated/molecule/openstack/tests/test_default.py
  test/scenarios/driver/delegated/molecule/vagrant/molecule.yml
  test/scenarios/driver/delegated/molecule/vagrant/playbook.yml
  test/scenarios/driver/delegated/molecule/vagrant/tests/test_default.py
Labels: CI

#2155 Add `--parallel` to functional test suite
  .travis.yml
  molecule/scenario.py
  pytest.ini
  test/functional/conftest.py
  test/functional/docker/test_scenarios.py
  test/functional/test_command.py
  test/scenarios/driver/azure/molecule/multi-node/tests/test_default.py
  test/scenarios/driver/delegated/molecule/docker/tests/test_default.py
  test/scenarios/driver/digitalocean/molecule/multi-node/tests/test_default.py
  test/scenarios/driver/docker/molecule/ansible-verifier/verify.yml
  test/scenarios/driver/docker/molecule/default/tests/test_default.py
  test/scenarios/driver/docker/molecule/multi-node/tests/test_bar.py
  test/scenarios/driver/docker/molecule/multi-node/tests/test_baz.py
  test/scenarios/driver/docker/molecule/multi-node/tests/test_default.py
  test/scenarios/driver/docker/molecule/multi-node/tests/test_foo.py
  test/unit/conftest.py
  tox.ini
Labels: CI

#2157 Add retry and back-off for dependency download
  CHANGELOG.rst
  molecule/dependency/ansible_galaxy.py
  molecule/dependency/base.py
  molecule/dependency/gilt.py
  molecule/dependency/shell.py
  test/functional/test_command.py
  test/scenarios/dependency/molecule/ansible-galaxy/requirements.yml
  test/scenarios/dependency/molecule/gilt/gilt.yml
  test/scenarios/dependency/molecule/shell/requirements.yml
  test/scenarios/dependency/molecule/shell/run.bash
Labels: important-change

#2162 Make sure unwanted payloads are skipped
  molecule/provisioner/ansible/plugins/filters/molecule_core.py
Labels: bug, important-change
