Repository ansible/molecule, pull requests merged in 2019-02, with the labels that each got.

#1674 Fixing #1488: Add feature to connect to windows host using `delegated driver` via winrm connection
  molecule/driver/delegated.py
  test/unit/driver/test_delegated.py
Labels: enhancement

#1640 sort scenarios based on directory name
  molecule/scenarios.py
  test/unit/test_scenarios_ordered.py
Labels: enhancement

#1733 Allow ansible-devel CI jobs to fail for now
  .travis.yml
Labels: CI

#1741 yapf updates
  molecule/migrate.py
  molecule/provisioner/ansible.py
  molecule/provisioner/ansible/plugins/libraries/molecule_vagrant.py
  test/unit/test_config.py
Labels: CI

#1749 Adapt functional testing to recent lint updates
  test/functional/.ansible-lint
  test/functional/conftest.py
  test/functional/docker/test_scenarios.py
  test/unit/command/init/test_template.py
Labels: CI

#1756 Extend Git clone depth to allow pbr to calculate non-duplicated prerelease versions
  .travis.yml
Labels: CI

#1691 List all python distribution extras in tox env declaration
  test/functional/conftest.py
  tox.ini
Labels: CI, enhancement

#1604 Fixing #1603 Add openssh-client to Docker image for git+ssh support
  build/Dockerfile
Labels: enhancement

#1716 doc: avoid MOLECULE_EPHEMERAL_DIRECTORY with tox
  doc/source/ci.rst
Labels: docs

#1759 Assure cleanup of python precompiled files with tox
  tox.ini
Labels: CI, enhancement

#1740 LXD prepare.yml: Install ca-certificates-cacert and ca-certificates-mozilla for openSUSE
  molecule/provisioner/ansible/playbooks/lxd/prepare.yml
Labels: enhancement

#1676 Add cleanup step.
  doc/source/usage.rst
  molecule/command/__init__.py
  molecule/command/cleanup.py
  molecule/config.py
  molecule/model/schema_v2.py
  molecule/provisioner/ansible.py
  molecule/provisioner/ansible_playbooks.py
  molecule/scenario.py
  molecule/scenarios.py
  molecule/shell.py
  test/functional/docker/test_scenarios.py
  test/functional/test_command.py
  test/scenarios/cleanup/molecule/default/cleanup.yml
  test/scenarios/cleanup/molecule/default/molecule.yml
  test/scenarios/cleanup/molecule/default/playbook.yml
  test/scenarios/cleanup/molecule/default/tests/test_default.py
  test/unit/command/test_cleanup.py
  test/unit/provisioner/test_ansible.py
  test/unit/provisioner/test_ansible_playbooks.py
  test/unit/test_scenario.py
  test/unit/test_scenarios.py
Labels: enhancement

#1535 Adds pid_mode feature to docker driver
  molecule/driver/docker.py
  molecule/model/schema_v2.py
  molecule/provisioner/ansible/playbooks/docker/create.yml
  test/resources/playbooks/docker/create.yml
  test/unit/model/v2/test_platforms_section.py
Labels: enhancement

#1783 💚👷🎨 Verify dist meta in PRs and cron jobs
  .travis.yml
  README.rst
Labels: CI

#1543 Add purge_networks arg to docker driver
  molecule/driver/docker.py
  molecule/model/schema_v2.py
  molecule/provisioner/ansible/playbooks/docker/create.yml
  test/resources/playbooks/docker/create.yml
  test/unit/model/v2/test_platforms_section.py
Labels: enhancement
