Repository ansible/molecule, pull requests merged in 2019-03, with the labels that each got.

#1795 Assure removal of __pycache__ before each tox run
  tox.ini
Labels: CI

#1794 Avoid using incompatible python with doc
  tox.ini
Labels: docs

#1533 Respect PY_COLORS variable
  doc/source/ci.rst
  molecule/logger.py
  molecule/util.py
  test/unit/test_logger.py
Labels: CI, docs, enhancement

#1797 🎨 Refactor building a docker image
  .dockerignore
  Dockerfile
  build/Dockerfile
  build/Makefile
  tox.ini
Labels: bug

#1769 Allow custom dockerfile location
  molecule/driver/docker.py
  molecule/model/schema_v2.py
  molecule/provisioner/ansible/playbooks/docker/create.yml
  test/resources/playbooks/docker/create.yml
  test/unit/model/v2/test_platforms_section.py
Labels: enhancement

#1745 Make default scenario name use the parent folder
  doc/source/ci.rst
  molecule/command/init/scenario.py
  molecule/config.py
  molecule/cookiecutter/molecule/{{cookiecutter.role_name}}/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/molecule.yml
  molecule/scenario.py
  test/scenarios/idempotence/molecule/raises/molecule.yml
  test/unit/test_config.py
Labels: important-change

#1814 Do not advertise support for EOL Ansible version
  doc/source/installation.rst
Labels: docs

#1815 Re-add openssh-client to docker image
  Dockerfile
Labels: docker-image

#1816 Manually add v2.20 change log
  CHANGELOG.rst
Labels: docs

#1829 Python 3.5 support in docs/package meta
  CHANGELOG.rst
  doc/source/installation.rst
  setup.cfg
Labels: docs

#1823 Avoid python libselinux bindings being hidden by tox
  bindep.txt
  doc/source/installation.rst
  tox.ini
Labels: bug

#1809 Fix custom dockerfile usage
  molecule/provisioner/ansible/playbooks/docker/create.yml
  test/resources/playbooks/docker/create.yml
Labels: bug

#1846 Avoid linting failure with flake8-docstrings
  .flake8
Labels: CI

#1852 Example for ignoring files/paths when using yamllint
  molecule/lint/yamllint.py
Labels: docs

#1838 Document sudo/user change + tags for image
  CHANGELOG.rst
  doc/source/examples.rst
  doc/source/installation.rst
Labels: docker-image, docs

#1857 CHANGELOG.rst: Fix bullet points
  CHANGELOG.rst
Labels: docs

#1854 Add some Prepare documentation
  molecule/command/prepare.py
Labels: docs

#1853 Document pre-release installation
  doc/source/installation.rst
Labels: docs

#1863 Update AUTHORS
  AUTHORS.rst
Labels: docs

#1866 Point to mailing list for usage questions
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: docs

#1865 Add FAQ and issue check to issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  doc/source/faq.rst
Labels: docs

#1864 Give virtualenv/setuptools warning on installation docs
  doc/source/conf.py
  doc/source/installation.rst
Labels: docs

#1875 Use sys_platform instead of platform_system
  setup.cfg
Labels: enhancement

#1644 fix: EC2 create security group in correct vpc
  test/resources/playbooks/ec2/create.yml
Labels: enhancement

#1839 Added ability to control no_log behavior
  molecule/cookiecutter/scenario/driver/azure/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/azure/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/delegated/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/delegated/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/ec2/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/ec2/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/gce/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/gce/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/linode/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/linode/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/lxc/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/lxc/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/openstack/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/openstack/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/provisioner/ansible.py
  molecule/provisioner/ansible/playbooks/docker/create.yml
  molecule/provisioner/ansible/playbooks/docker/destroy.yml
  molecule/provisioner/ansible/playbooks/lxd/create.yml
  molecule/provisioner/ansible/playbooks/lxd/destroy.yml
  molecule/provisioner/ansible/playbooks/vagrant/create.yml
  molecule/provisioner/ansible/playbooks/vagrant/destroy.yml
  test/resources/playbooks/azure/create.yml
  test/resources/playbooks/azure/destroy.yml
  test/resources/playbooks/docker/create.yml
  test/resources/playbooks/docker/destroy.yml
  test/resources/playbooks/ec2/create.yml
  test/resources/playbooks/ec2/destroy.yml
  test/resources/playbooks/gce/create.yml
  test/resources/playbooks/gce/destroy.yml
  test/resources/playbooks/linode/create.yml
  test/resources/playbooks/linode/destroy.yml
  test/resources/playbooks/lxc/create.yml
  test/resources/playbooks/lxc/destroy.yml
  test/resources/playbooks/lxd/create.yml
  test/resources/playbooks/lxd/destroy.yml
  test/resources/playbooks/openstack/create.yml
  test/resources/playbooks/openstack/destroy.yml
  test/resources/playbooks/vagrant/create.yml
  test/resources/playbooks/vagrant/destroy.yml
  test/scenarios/side_effect/molecule/default/side_effect.yml
  test/unit/provisioner/test_ansible.py
Labels: ux

#1862 Fix/Lint Inspec Verify Playbook
  molecule/cookiecutter/scenario/verifier/inspec/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/verify.yml
Labels: bug

#1581 added an alternate Jenkinsfile and comments on Multibranch pipelines.
  doc/source/ci.rst
Labels: docs
