Repository ansible/molecule, pull requests merged in 2019-05, with the labels that each got.

#2037 Add Git to run time of Docker image
  Dockerfile
Labels: docker

#2036 PR + Governance updates to CONTRIBUTING.md
  CONTRIBUTING.rst
Labels: docs

#2046 Place upper bounds on inspec/rubcop
  .travis.yml
  CHANGELOG.rst
Labels: CI

#2066 Add note about change log entry to Github template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#2072 Bump pytest* dependencies
  test/unit/model/v2/test_pre_validate.py
  tox.ini
Labels: CI

#2074 Removed emoji from github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/proposal.md
  .github/ISSUE_TEMPLATE/security_bug_report.md
Labels: CI

#2076 Add paramiko dependency (made optional in Ansible 2.8+)
  setup.cfg
Labels: bug, critical

#2078 Choose higher bound on testinfra
  setup.cfg
Labels: critical
