Repository ansible/molecule, pull requests merged in 2019-06, with the labels that each got.

#2092 Fix Ansible 2.8 deprecation warnings in provisioner playbook
  molecule/provisioner/ansible/playbooks/docker/create.yml
Labels: CI

#1996 Enable use of pre-commit for linting
  .github/CODEOWNERS
  .pre-commit-config.yaml
  molecule/cookiecutter/scenario/driver/digitalocean/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  test/resources/invalid_role_template/bad_format/README.md
  tox.ini
Labels: CI

#2098 Added podman driver for molecule
  molecule/config.py
  molecule/cookiecutter/molecule/{{cookiecutter.role_name}}/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/molecule.yml
  molecule/driver/podman.py
  molecule/model/schema_v2.py
  molecule/provisioner/ansible/playbooks/podman/create.yml
  molecule/provisioner/ansible/playbooks/podman/destroy.yml
  test/unit/test_config.py
Labels: enhancement

#2103 Bump cerberus
  setup.cfg
Labels: CI

#2107 Enable profiling during test execution
  tox.ini
Labels: CI

#2112 Fix Gitlab CI config in docs
  docs/ci.rst
Labels: docs

#2120 Remove use of tox-venv
  .travis.yml
Labels: CI

#2127 Adopt use of XDG cache directories
  molecule/scenario.py
Labels: bug, critical

#2124 Fix docker module deprecations
  molecule/provisioner/ansible/playbooks/docker/create.yml
  test/resources/playbooks/docker/create.yml
Labels: docker
