Repository ansible/molecule, pull requests merged in 2019-10, with the labels that each got.

#2339 Modify the type of winrm_server_cert_validation described in the docu…
  molecule/driver/delegated.py
Labels: needs-update

#2362 Correct python package installation on Dockerfiles
  molecule/cookiecutter/scenario/driver/docker/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/Dockerfile.j2
  molecule/cookiecutter/scenario/driver/podman/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/Dockerfile.j2
  molecule/test/resources/custom_scenario_template/docker/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/Dockerfile.j2
  molecule/test/resources/playbooks/docker/Dockerfile.j2
Labels: hacktoberfest

#1600 Fixing #1556 VERR_ACCESS_DENIED
  molecule/driver/vagrant.py
Labels: enhancement, help wanted, vagrant

#2360 Make default Dockerfile embedded
  CHANGELOG.rst
  docs/examples.rst
  molecule/cookiecutter/scenario/driver/podman/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/Dockerfile.j2
  molecule/data/Dockerfile.j2
  molecule/provisioner/ansible/playbooks/docker/create.yml
  molecule/provisioner/ansible/playbooks/podman/create.yml
  molecule/test/resources/custom_scenario_template/docker/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/Dockerfile.j2
Labels: bump, hacktoberfest

#2369 Bumped linting
  .pre-commit-config.yaml
  .yamllint
Labels: skip-changelist

#2367 Enable release drafter
  .github/workflows/release-drafter.yml
Labels: skip-changelist

#2371 Test ansible 2.9 from stable-2.9
  tox.ini
Labels: CI, bump, critical, skip-changelist

#2365 fix deprecation in generated code for hetznercloud driver
  molecule/cookiecutter/scenario/driver/hetznercloud/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/test/resources/playbooks/hetznercloud/destroy.yml
Labels: hacktoberfest

#2377 Add note about random instance IDs
  docs/faq.rst
Labels: docs

#2368 Enable testing of dockerfile template
  .travis.yml
  molecule/data/validate-dockerfile.yml
  tox.ini
Labels: docker, hacktoberfest

#2378 Add release drafter config file
  .github/release-drafter.yml
Labels: docs

#2370 Added instance_profile_name to ec2 driver
  molecule/cookiecutter/scenario/driver/ec2/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/driver/ec2.py
  molecule/test/resources/playbooks/ec2/create.yml
  molecule/test/scenarios/driver/ec2/molecule/default/molecule.yml
  molecule/test/scenarios/driver/ec2/molecule/multi-node/molecule.yml
  molecule/test/unit/driver/test_ec2.py
Labels: enhancement

#2382 Implement tox setup idempotency test
  .travis.yml
Labels: test

#2384 Reverts setuptools workaround
  pyproject.toml
Labels: packaging

#2385 Made base image fully configurable
  molecule/test/functional/docker/test_scenarios.py
  molecule/test/resources/molecule_docker.yml
  molecule/test/resources/playbooks/delegated/create/docker.yml
  molecule/test/scenarios/cleanup/molecule/default/molecule.yml
  molecule/test/scenarios/dependency/molecule/ansible-galaxy/molecule.yml
  molecule/test/scenarios/dependency/molecule/gilt/molecule.yml
  molecule/test/scenarios/dependency/molecule/shell/molecule.yml
  molecule/test/scenarios/driver/docker/molecule/ansible-verifier/molecule.yml
  molecule/test/scenarios/driver/docker/molecule/default/molecule.yml
  molecule/test/scenarios/driver/docker/molecule/multi-node/molecule.yml
  molecule/test/scenarios/host_group_vars/molecule/default/molecule.yml
  molecule/test/scenarios/host_group_vars/molecule/links/molecule.yml
  molecule/test/scenarios/idempotence/molecule/raises/molecule.yml
  molecule/test/scenarios/interpolation/molecule/default/molecule.yml
  molecule/test/scenarios/overrride_driver/molecule/default/molecule.yml
  molecule/test/scenarios/plugins/molecule/default/molecule.yml
  molecule/test/scenarios/side_effect/molecule/default/molecule.yml
  molecule/test/scenarios/test_destroy_strategy/molecule/default/molecule.yml
  molecule/test/scenarios/verifier/molecule/testinfra-pre-commit/molecule.yml
  molecule/test/scenarios/verifier/molecule/testinfra/molecule.yml
  molecule/test/unit/model/v2/test_pre_validate.py
  tox.ini
Labels: test

#2392 Run unit tests against Python 3.8
  .travis.yml
Labels: test

#2390 ec2 provider: Add support for specifying ssh keypair
  molecule/cookiecutter/scenario/driver/ec2/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
Labels: driver-ec2, enhancement

#2391 Remove Hetzner Cloud driver from core
  .travis.yml
  CHANGELOG.rst
  Dockerfile
  contrib/tokenmgmr.py
  docs/configuration.rst
  molecule/cookiecutter/molecule/{{cookiecutter.role_name}}/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/molecule.yml
  molecule/cookiecutter/scenario/driver/hetznercloud/cookiecutter.json
  molecule/cookiecutter/scenario/driver/hetznercloud/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/hetznercloud/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/hetznercloud/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/hetznercloud/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/playbook.yml
  molecule/cookiecutter/scenario/driver/hetznercloud/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/prepare.yml
  molecule/driver/hetznercloud.py
  molecule/model/schema_v2.py
  molecule/test/functional/conftest.py
  molecule/test/functional/test_command.py
  molecule/test/resources/playbooks/hetznercloud/create.yml
  molecule/test/resources/playbooks/hetznercloud/destroy.yml
  molecule/test/scenarios/driver/hetznercloud/molecule/default/molecule.yml
  molecule/test/scenarios/driver/hetznercloud/molecule/default/playbook.yml
  molecule/test/scenarios/driver/hetznercloud/molecule/default/tests/test_default.py
  molecule/test/scenarios/driver/hetznercloud/molecule/multi-node/molecule.yml
  molecule/test/scenarios/driver/hetznercloud/molecule/multi-node/playbook.yml
  molecule/test/scenarios/driver/hetznercloud/molecule/multi-node/tests/test_default.py
  molecule/test/unit/cookiecutter/test_molecule.py
  molecule/test/unit/driver/test_hetznercloud.py
  molecule/test/unit/model/v2/test_platforms_section.py
  setup.cfg
  tox.ini
Labels: driver-hetznercloud, major

#2395 Point to travis-ci.com in docs
  docs/ci.rst
Labels: docs

#2398 test: implement workaround for galaxy-install 401 errors
  conftest.py
Labels: test

#2401 Moved digitalocean driver to molecule-digitalocean
  docs/configuration.rst
  molecule/cookiecutter/molecule/{{cookiecutter.role_name}}/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/molecule.yml
  molecule/cookiecutter/scenario/driver/digitalocean/cookiecutter.json
  molecule/cookiecutter/scenario/driver/digitalocean/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/digitalocean/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/digitalocean/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/digitalocean/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/playbook.yml
  molecule/cookiecutter/scenario/driver/digitalocean/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/prepare.yml
  molecule/driver/digitalocean.py
  molecule/test/functional/conftest.py
  molecule/test/functional/test_command.py
  molecule/test/resources/playbooks/digitalocean/create.yml
  molecule/test/resources/playbooks/digitalocean/destroy.yml
  molecule/test/scenarios/driver/digitalocean/molecule/default/molecule.yml
  molecule/test/scenarios/driver/digitalocean/molecule/default/playbook.yml
  molecule/test/scenarios/driver/digitalocean/molecule/default/tests/test_default.py
  molecule/test/scenarios/driver/digitalocean/molecule/multi-node/molecule.yml
  molecule/test/scenarios/driver/digitalocean/molecule/multi-node/playbook.yml
  molecule/test/scenarios/driver/digitalocean/molecule/multi-node/tests/test_default.py
  molecule/test/unit/cookiecutter/test_molecule.py
  molecule/test/unit/driver/test_digitalocean.py
  molecule/test/unit/model/v2/test_driver_section.py
  molecule/test/unit/test_config.py
  setup.cfg
Labels: major, packaging

#2406 Moved gce driver to molecule-gce
  Dockerfile
  docs/configuration.rst
  docs/getting-started.rst
  molecule/cookiecutter/molecule/{{cookiecutter.role_name}}/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/molecule.yml
  molecule/cookiecutter/scenario/driver/gce/cookiecutter.json
  molecule/cookiecutter/scenario/driver/gce/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/gce/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/gce/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/gce/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/playbook.yml
  molecule/cookiecutter/scenario/driver/gce/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/prepare.yml
  molecule/driver/gce.py
  molecule/test/functional/conftest.py
  molecule/test/functional/test_command.py
  molecule/test/resources/playbooks/delegated/create.yml
  molecule/test/resources/playbooks/delegated/create/gce.yml
  molecule/test/resources/playbooks/delegated/destroy.yml
  molecule/test/resources/playbooks/delegated/destroy/gce.yml
  molecule/test/resources/playbooks/delegated/inventory/group_vars/all/all.yml
  molecule/test/resources/playbooks/gce/create.yml
  molecule/test/resources/playbooks/gce/destroy.yml
  molecule/test/scenarios/driver/gce/molecule/default/molecule.yml
  molecule/test/scenarios/driver/gce/molecule/default/playbook.yml
  molecule/test/scenarios/driver/gce/molecule/default/prepare.yml
  molecule/test/scenarios/driver/gce/molecule/default/tests/test_default.py
  molecule/test/scenarios/driver/gce/molecule/multi-node/molecule.yml
  molecule/test/scenarios/driver/gce/molecule/multi-node/playbook.yml
  molecule/test/scenarios/driver/gce/molecule/multi-node/prepare.yml
  molecule/test/scenarios/driver/gce/molecule/multi-node/tests/__init__.py
  molecule/test/scenarios/driver/gce/molecule/multi-node/tests/test_default.py
  molecule/test/unit/cookiecutter/test_molecule.py
  molecule/test/unit/driver/test_gce.py
  molecule/test/unit/model/v2/test_driver_section.py
  molecule/test/unit/test_config.py
  setup.cfg
  tox.ini
Labels: major, packaging

#2407 Moved ec2 driver to molecule-ec2
  Dockerfile
  docs/configuration.rst
  docs/getting-started.rst
  molecule/cookiecutter/molecule/{{cookiecutter.role_name}}/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/molecule.yml
  molecule/cookiecutter/scenario/driver/ec2/cookiecutter.json
  molecule/cookiecutter/scenario/driver/ec2/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/ec2/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/ec2/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/ec2/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/playbook.yml
  molecule/cookiecutter/scenario/driver/ec2/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/prepare.yml
  molecule/driver/ec2.py
  molecule/test/functional/conftest.py
  molecule/test/functional/test_command.py
  molecule/test/resources/playbooks/delegated/create.yml
  molecule/test/resources/playbooks/delegated/create/ec2.yml
  molecule/test/resources/playbooks/delegated/destroy.yml
  molecule/test/resources/playbooks/delegated/destroy/ec2.yml
  molecule/test/resources/playbooks/delegated/inventory/group_vars/all/all.yml
  molecule/test/resources/playbooks/ec2/create.yml
  molecule/test/resources/playbooks/ec2/destroy.yml
  molecule/test/scenarios/driver/ec2/molecule/default/molecule.yml
  molecule/test/scenarios/driver/ec2/molecule/default/playbook.yml
  molecule/test/scenarios/driver/ec2/molecule/default/prepare.yml
  molecule/test/scenarios/driver/ec2/molecule/default/tests/test_default.py
  molecule/test/scenarios/driver/ec2/molecule/multi-node/molecule.yml
  molecule/test/scenarios/driver/ec2/molecule/multi-node/playbook.yml
  molecule/test/scenarios/driver/ec2/molecule/multi-node/prepare.yml
  molecule/test/scenarios/driver/ec2/molecule/multi-node/tests/__init__.py
  molecule/test/scenarios/driver/ec2/molecule/multi-node/tests/test_default.py
  molecule/test/unit/command/init/test_scenario.py
  molecule/test/unit/cookiecutter/test_molecule.py
  molecule/test/unit/driver/test_ec2.py
  molecule/test/unit/model/v2/test_driver_section.py
  molecule/test/unit/test_config.py
  setup.cfg
  tox.ini
Labels: driver-ec2, major, packaging

#2411 Clean up outdated docs
  CONTRIBUTING.rst
  docs/development.rst
  docs/examples.rst
  docs/testing.rst
Labels: docs

#2413 Moved openstack driver to molecule-openstack
  Dockerfile
  docs/ci.rst
  docs/conf.py
  docs/configuration.rst
  molecule/cookiecutter/molecule/{{cookiecutter.role_name}}/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/molecule.yml
  molecule/cookiecutter/scenario/driver/openstack/cookiecutter.json
  molecule/cookiecutter/scenario/driver/openstack/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/openstack/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/openstack/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/openstack/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/playbook.yml
  molecule/cookiecutter/scenario/driver/openstack/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/prepare.yml
  molecule/driver/openstack.py
  molecule/test/functional/conftest.py
  molecule/test/functional/test_command.py
  molecule/test/resources/playbooks/delegated/create.yml
  molecule/test/resources/playbooks/delegated/create/openstack.yml
  molecule/test/resources/playbooks/delegated/destroy.yml
  molecule/test/resources/playbooks/delegated/destroy/openstack.yml
  molecule/test/resources/playbooks/delegated/inventory/group_vars/all/all.yml
  molecule/test/resources/playbooks/openstack/create.yml
  molecule/test/resources/playbooks/openstack/destroy.yml
  molecule/test/scenarios/driver/openstack/molecule/default/molecule.yml
  molecule/test/scenarios/driver/openstack/molecule/default/playbook.yml
  molecule/test/scenarios/driver/openstack/molecule/default/prepare.yml
  molecule/test/scenarios/driver/openstack/molecule/default/tests/test_default.py
  molecule/test/scenarios/driver/openstack/molecule/multi-node/molecule.yml
  molecule/test/scenarios/driver/openstack/molecule/multi-node/playbook.yml
  molecule/test/scenarios/driver/openstack/molecule/multi-node/prepare.yml
  molecule/test/scenarios/driver/openstack/molecule/multi-node/tests/__init__.py
  molecule/test/scenarios/driver/openstack/molecule/multi-node/tests/test_default.py
  molecule/test/unit/cookiecutter/test_molecule.py
  molecule/test/unit/driver/test_openstack.py
  molecule/test/unit/model/v2/test_driver_section.py
  molecule/test/unit/test_config.py
  setup.cfg
  tox.ini
Labels: major, openstack, packaging

#2416 Disable DCO
  .github/dco.yml
  CONTRIBUTING.rst
Labels: enhancement

#2418 Bump ansible-lint
  setup.cfg
Labels: packaging

#2417 Fix wrong template path for drivers
  molecule/command/init/role.py
Labels: bug, packaging

#2415 New Ansible style docs layout
  CHANGELOG.rst
  README.rst
  docs/conf.py
  docs/examples.rst
  docs/getting-started.rst
  docs/index.rst
  docs/quick-start.rst
  docs/upgrade.rst
  docs/usage.rst
  tox.ini
Labels: docs

#2419 Fixed molecule init scenario
  molecule/command/init/scenario.py
Labels: bug

#2422 docs: fix removed porting guide
  docs/index.rst
Labels: docs
