Repository ansible/molecule, pull requests merged in 2019-11, with the labels that each got.

#2427 updated docker_image buildargs with new format build.args
  molecule/provisioner/ansible/playbooks/docker/create.yml
Labels: bug, docker

#2428 docs: fixed broken link to galaxy docs
  docs/getting-started.rst
  molecule/dependency/ansible_galaxy.py
Labels: docs, test

#2423 docs: avoid simplejson error
  setup.cfg
Labels: docs

#2436 lint refresh
  .pre-commit-config.yaml
  molecule/test/unit/test_config.py
Labels: skip-changelist, test

#2437 Remove anyconfig dependency
  molecule/config.py
  molecule/dependency/ansible_galaxy.py
  molecule/dependency/gilt.py
  molecule/dependency/shell.py
  molecule/lint/yamllint.py
  molecule/model/schema_v2.py
  molecule/provisioner/ansible.py
  molecule/provisioner/lint/ansible_lint.py
  molecule/test/unit/conftest.py
  molecule/test/unit/test_util.py
  molecule/util.py
  molecule/verifier/ansible.py
  molecule/verifier/lint/flake8.py
  molecule/verifier/lint/precommit.py
  molecule/verifier/lint/rubocop.py
  molecule/verifier/lint/yamllint.py
  molecule/verifier/testinfra.py
  setup.cfg
Labels: bug, packaging

#2342 Use ansible-galaxy to create roles
  molecule/command/init/role.py
  molecule/cookiecutter/molecule/{{cookiecutter.role_name}}/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/molecule.yml
  molecule/cookiecutter/role/cookiecutter.json
  molecule/cookiecutter/role/{{cookiecutter.role_name}}/README.md
  molecule/cookiecutter/role/{{cookiecutter.role_name}}/defaults/main.yml
  molecule/cookiecutter/role/{{cookiecutter.role_name}}/handlers/main.yml
  molecule/cookiecutter/role/{{cookiecutter.role_name}}/meta/main.yml
  molecule/cookiecutter/role/{{cookiecutter.role_name}}/tasks/main.yml
  molecule/cookiecutter/role/{{cookiecutter.role_name}}/vars/main.yml
  molecule/test/functional/.ansible-lint
  molecule/test/functional/docker/test_scenarios.py
  molecule/test/resources/custom_role_template/cookiecutter.json
  molecule/test/resources/custom_role_template/{{cookiecutter.role_name}}/README.md
  molecule/test/unit/command/init/test_role.py
  setup.cfg
Labels: major

#2443 Remove GitHub Actions
  .github/workflows/release-drafter.yml
Labels: skip-changelist

#2454 Disable podman testing on MacOS
  molecule/test/functional/conftest.py
Labels: skip-changelist

#2452 Removed ansible27 with py38 testing
  .travis.yml
  tox.ini
Labels: skip-changelist
