Repository ansible/molecule, pull requests merged in 2019-08, with the labels that each got.

#2189 Bumps pre-commit
  .pre-commit-config.yaml
Labels: CI

#2148 Allows identifying the EC2 instances through the AWS console
  molecule/cookiecutter/scenario/driver/ec2/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
Labels: driver-ec2

#1811 Add Hetzner Cloud driver
  .travis.yml
  Dockerfile
  contrib/tokenmgmr.py
  docs/configuration.rst
  molecule/config.py
  molecule/cookiecutter/molecule/{{cookiecutter.role_name}}/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/molecule.yml
  molecule/cookiecutter/scenario/driver/hetznercloud/cookiecutter.json
  molecule/cookiecutter/scenario/driver/hetznercloud/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/hetznercloud/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/hetznercloud/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/hetznercloud/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/playbook.yml
  molecule/cookiecutter/scenario/driver/hetznercloud/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/prepare.yml
  molecule/driver/hetznercloud.py
  molecule/model/schema_v2.py
  molecule/scenario.py
  setup.cfg
  test/functional/conftest.py
  test/functional/test_command.py
  test/resources/playbooks/hetznercloud/create.yml
  test/resources/playbooks/hetznercloud/destroy.yml
  test/scenarios/driver/hetznercloud/molecule/default/molecule.yml
  test/scenarios/driver/hetznercloud/molecule/default/playbook.yml
  test/scenarios/driver/hetznercloud/molecule/default/tests/test_default.py
  test/scenarios/driver/hetznercloud/molecule/multi-node/molecule.yml
  test/scenarios/driver/hetznercloud/molecule/multi-node/playbook.yml
  test/scenarios/driver/hetznercloud/molecule/multi-node/tests/test_default.py
  test/unit/cookiecutter/test_molecule.py
  test/unit/driver/test_hetznercloud.py
  test/unit/model/v2/test_platforms_section.py
  test/unit/test_config.py
  tox.ini
Labels: enhancement

#2192 docker: Adds sysctl parameter
  CHANGELOG.rst
  molecule/driver/docker.py
  molecule/model/schema_v2.py
  molecule/provisioner/ansible/playbooks/docker/create.yml
  test/unit/model/v2/test_platforms_section.py
Labels: docker

#2197 Remove references to volume_mounts from docs
  molecule/driver/docker.py
  molecule/driver/podman.py
Labels: docker

#2198 Bumps minimal testinfra version to 3.0.6
  CHANGELOG.rst
  setup.cfg
Labels: bug, critical, testinfra

#1889 Add user arg for docker driver
  molecule/driver/docker.py
  molecule/model/schema_v2.py
  molecule/provisioner/ansible/playbooks/docker/create.yml
  test/resources/playbooks/docker/create.yml
  test/unit/model/v2/test_platforms_section.py
Labels: docker

#2202 Fixed invalid use of env params on Travis
  .travis.yml
Labels: CI

#2209 Removed obsolete metadata-validation
  .travis.yml
  docs/testing.rst
Labels: CI, bug

#2208 Revert anyconfig version to last known good
  setup.cfg
Labels: packaging

#2206 Adds retries to image building tasks
  molecule/provisioner/ansible/playbooks/docker/create.yml
  molecule/provisioner/ansible/playbooks/podman/create.yml
  test/resources/playbooks/docker/create.yml
Labels: CI

#2217 Fix floating IP deletion in openstack driver
  molecule/cookiecutter/scenario/driver/openstack/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/openstack/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  test/resources/playbooks/delegated/create/openstack.yml
  test/resources/playbooks/delegated/destroy/openstack.yml
  test/resources/playbooks/openstack/create.yml
  test/resources/playbooks/openstack/destroy.yml
Labels: openstack

#2234 Allow configurable Azure Region
  molecule/cookiecutter/scenario/driver/azure/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
Labels: azure

#2219 Makes molecule drivers plugins
  molecule/api.py
  molecule/command/create.py
  molecule/command/destroy.py
  molecule/command/init/role.py
  molecule/command/init/scenario.py
  molecule/command/prepare.py
  molecule/command/test.py
  molecule/config.py
  molecule/driver/azure.py
  molecule/driver/delegated.py
  molecule/driver/digitalocean.py
  molecule/driver/docker.py
  molecule/driver/ec2.py
  molecule/driver/gce.py
  molecule/driver/hetznercloud.py
  molecule/driver/linode.py
  molecule/driver/lxc.py
  molecule/driver/lxd.py
  molecule/driver/openstack.py
  molecule/driver/podman.py
  molecule/driver/vagrant.py
  molecule/model/schema_v2.py
  setup.cfg
  test/unit/test_config.py
Labels: enhancement, packaging

#2215 Run dependency before lint on test_sequence
  CHANGELOG.rst
  molecule/command/lint.py
  molecule/command/test.py
  molecule/config.py
  molecule/scenario.py
  test/unit/test_scenario.py
  test/unit/test_scenarios.py
Labels: bug

#2154 Pull docker containers at launch as well as build.
  molecule/provisioner/ansible/playbooks/docker/create.yml
  test/resources/playbooks/docker/create.yml
Labels: docker

#2229 Fix container building
  .travis.yml
  Dockerfile
  tox.ini
  utils/build-docker.py
Labels: bug, packaging

#2243 azure: assure we respect locally configured region
  molecule/test/resources/playbooks/azure/create.yml
  molecule/test/resources/playbooks/azure/destroy.yml
  molecule/test/scenarios/driver/azure/molecule/multi-node/molecule.yml
Labels: azure

#2259 Cache loaded drivers and adopt lru_cache
  molecule/api.py
  molecule/config.py
  molecule/provisioner/ansible.py
  molecule/provisioner/base.py
  molecule/util.py
  molecule/verifier/base.py
  setup.cfg
Labels: enhancement

#2255 travis: switch to 2 shards instead of 3
  .travis.yml
Labels: CI

#2252 Removal of embedded azure driver
  docs/configuration.rst
  docs/getting-started.rst
  molecule/cookiecutter/molecule/{{cookiecutter.role_name}}/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/molecule.yml
  molecule/cookiecutter/scenario/driver/azure/cookiecutter.json
  molecule/cookiecutter/scenario/driver/azure/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/azure/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/azure/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/azure/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/playbook.yml
  molecule/driver/azure.py
  molecule/test/functional/conftest.py
  molecule/test/functional/test_command.py
  molecule/test/resources/playbooks/azure/create.yml
  molecule/test/resources/playbooks/azure/destroy.yml
  molecule/test/scenarios/driver/azure/molecule/default/molecule.yml
  molecule/test/scenarios/driver/azure/molecule/default/playbook.yml
  molecule/test/scenarios/driver/azure/molecule/default/tests/test_default.py
  molecule/test/scenarios/driver/azure/molecule/multi-node/molecule.yml
  molecule/test/scenarios/driver/azure/molecule/multi-node/playbook.yml
  molecule/test/scenarios/driver/azure/molecule/multi-node/prepare.yml
  molecule/test/scenarios/driver/azure/molecule/multi-node/tests/__init__.py
  molecule/test/scenarios/driver/azure/molecule/multi-node/tests/test_default.py
  molecule/test/unit/cookiecutter/test_molecule.py
  molecule/test/unit/driver/test_azure.py
  molecule/test/unit/model/v2/test_driver_section.py
  molecule/test/unit/test_config.py
  setup.cfg
  tox.ini
Labels: breaking-change

#2253 Makes driver loading more resilient
  molecule/api.py
  molecule/test/unit/test_config.py
Labels: bug
