Repository ansible/molecule, pull requests merged in 2019-01, with the labels that each got.

#1458 Add Linode driver (v3 API)
  doc/source/configuration.rst
  molecule/config.py
  molecule/cookiecutter/molecule/{{cookiecutter.role_name}}/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/molecule.yml
  molecule/cookiecutter/scenario/driver/linode/cookiecutter.json
  molecule/cookiecutter/scenario/driver/linode/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/linode/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/linode/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/cookiecutter/scenario/driver/linode/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/playbook.yml
  molecule/driver/linode.py
  molecule/model/schema_v2.py
  setup.cfg
  test/functional/conftest.py
  test/functional/test_command.py
  test/resources/playbooks/linode/create.yml
  test/resources/playbooks/linode/destroy.yml
  test/scenarios/driver/linode/molecule/default/molecule.yml
  test/scenarios/driver/linode/molecule/default/playbook.yml
  test/scenarios/driver/linode/molecule/default/tests/test_default.py
  test/scenarios/driver/linode/molecule/multi-node/molecule.yml
  test/scenarios/driver/linode/molecule/multi-node/playbook.yml
  test/scenarios/driver/linode/molecule/multi-node/tests/test_default.py
  test/unit/cookiecutter/test_molecule.py
  test/unit/driver/test_linode.py
  test/unit/model/v2/test_platforms_section.py
  test/unit/test_config.py
Labels: enhancement

#1684 Remove bad test docs and fix typo.
  doc/source/testing.rst
  molecule/provisioner/ansible.py
Labels: docs, tests

#1500 Fix delegate
  molecule/cookiecutter/scenario/driver/delegated/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/driver/delegated.py
Labels: bug, docs, enhancement

#1677 Clarify some implications of Red Hat move in docs.
  CONTRIBUTING.rst
Labels: docs

#1685 Remove `sudo pip ...`
  molecule/cookiecutter/scenario/driver/azure/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/docker/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/ec2/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/gce/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/linode/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/lxc/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/lxd/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/openstack/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/vagrant/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/driver/ec2.py
Labels: docs

#1695 1694 lint errors
  .flake8
  lint-requirements.txt
  molecule/command/matrix.py
  molecule/dependency/shell.py
  molecule/interpolation.py
  molecule/provisioner/ansible_playbook.py
  molecule/util.py
  molecule/verifier/goss.py
  molecule/verifier/testinfra.py
  requirements.txt
  test-requirements.txt
  test/functional/docker/test_scenarios.py
  test/scenarios/driver/vagrant/molecule/multi-node/tests/test_instance-1.py
  test/scenarios/driver/vagrant/molecule/multi-node/tests/test_instance-2.py
  tox.ini
Labels: tests

#1693 closes #1692 align python versions on ansible tox
  tox.ini
Labels: CI

#1707 Run Sphinx in nitpick mode with warning as errors
  CONTRIBUTING.rst
  doc/Makefile
  doc/source/ci.rst
  doc/source/configuration.rst
  molecule/config.py
  molecule/driver/delegated.py
  molecule/driver/docker.py
  molecule/state.py
  tox.ini
Labels: CI, docs

#1720 Fix all links
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGELOG.rst
  CONTRIBUTING.rst
  README.rst
  doc/source/development.rst
  doc/source/faq.rst
  molecule/dependency/ansible_galaxy.py
  molecule/dependency/gilt.py
  molecule/driver/azure.py
  molecule/driver/docker.py
  molecule/driver/ec2.py
  molecule/driver/gce.py
  molecule/driver/lxc.py
  molecule/driver/lxd.py
  molecule/driver/openstack.py
  molecule/provisioner/ansible.py
  molecule/verifier/testinfra.py
Labels: docs
