Repository ansible/molecule, pull requests merged in 2019-09, with the labels that each got.

#2258 fix(provisioner): Expand ANSIBLE_ variables with Ansible default locations
  CHANGELOG.rst
  molecule/provisioner/ansible.py
  molecule/provisioner/ansible/plugins/filter/molecule_core.py
  molecule/provisioner/ansible/plugins/modules/molecule_vagrant.py
  molecule/test/unit/provisioner/test_ansible.py
Labels: breaking-change

#2284 drivers: refactored sanity_check
  molecule/api.py
  molecule/config.py
  molecule/driver/docker.py
  molecule/driver/hetznercloud.py
  molecule/driver/podman.py
  molecule/provisioner/ansible.py
  molecule/provisioner/base.py
  molecule/state.py
  molecule/test/unit/provisioner/test_ansible_playbook.py
  molecule/util.py
  molecule/verifier/base.py
Labels: bump

#2288 refactoring: transformed verifiers into plugins
  molecule/api.py
  molecule/command/init/role.py
  molecule/command/init/scenario.py
  molecule/config.py
  molecule/test/unit/test_api.py
  molecule/test/unit/test_config.py
  molecule/verifier/ansible.py
  molecule/verifier/base.py
  molecule/verifier/goss.py
  molecule/verifier/inspec.py
  molecule/verifier/testinfra.py
  setup.cfg
Labels: bump

#2289 Disable deprecation warnings from own dependencies
  pytest.ini
Labels: bump

#2281 refactoring: driver listing
  .pre-commit-config.yaml
  molecule/api.py
  molecule/config.py
  molecule/driver/base.py
  molecule/driver/delegated.py
  molecule/driver/digitalocean.py
  molecule/driver/docker.py
  molecule/driver/ec2.py
  molecule/driver/gce.py
  molecule/driver/hetznercloud.py
  molecule/driver/linode.py
  molecule/driver/lxc.py
  molecule/driver/lxd.py
  molecule/driver/openstack.py
  molecule/driver/podman.py
  molecule/driver/vagrant.py
  molecule/test/unit/test_api.py
  molecule/test/unit/test_config.py
  molecule/verifier/base.py
  setup.cfg
Labels: bump

#2292 refactoring: verifiers should expose their own linters
  molecule/api.py
  molecule/command/init/role.py
  molecule/command/init/scenario.py
  molecule/config.py
  molecule/verifier/base.py
  molecule/verifier/goss.py
  molecule/verifier/inspec.py
  molecule/verifier/testinfra.py
Labels: bump

#2297 deps: refresh click dependencies
  setup.cfg
Labels: bump

#2295 Fix auto-completion of choices
  molecule/command/create.py
  molecule/command/destroy.py
  molecule/command/init/role.py
  molecule/command/init/scenario.py
  molecule/command/prepare.py
  molecule/command/test.py
Labels: bump

#2296 deps: remove pinning of anyconfig
  setup.cfg
Labels: bump

#2294 refactoring: each verifier to expose its own schema
  molecule/model/schema_v2.py
  molecule/verifier/ansible.py
  molecule/verifier/base.py
  molecule/verifier/goss.py
  molecule/verifier/inspec.py
  molecule/verifier/testinfra.py
Labels: bump

#2298 verifier: goss removed
  CHANGELOG.rst
  CONTRIBUTING.rst
  docs/configuration.rst
  molecule/cookiecutter/scenario/verifier/goss/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/verify.yml
  molecule/model/schema_v2.py
  molecule/test/functional/docker/test_scenarios.py
  molecule/test/scenarios/verifier/molecule/goss/molecule.yml
  molecule/test/scenarios/verifier/molecule/goss/verify.yml
  molecule/test/unit/cookiecutter/test_molecule.py
  molecule/test/unit/model/v2/test_verifier_section.py
  molecule/test/unit/test_api.py
  molecule/test/unit/test_config.py
  molecule/test/unit/verifier/lint/test_yamllint.py
  molecule/test/unit/verifier/test_goss.py
  molecule/verifier/goss.py
  molecule/verifier/lint/yamllint.py
  setup.cfg
Labels: bump

#2276 Migrate to new linode_v4 module
  CHANGELOG.rst
  molecule/cookiecutter/molecule/{{cookiecutter.role_name}}/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/molecule.yml
  molecule/cookiecutter/scenario/driver/linode/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/linode/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/linode/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/driver/linode.py
  molecule/model/schema_v2.py
  molecule/test/functional/conftest.py
  molecule/test/resources/playbooks/linode/create.yml
  molecule/test/resources/playbooks/linode/destroy.yml
  molecule/test/scenarios/driver/linode/molecule/default/molecule.yml
  molecule/test/scenarios/driver/linode/molecule/multi-node/molecule.yml
  molecule/test/unit/driver/test_linode.py
  molecule/test/unit/model/v2/test_platforms_section.py
  setup.cfg
Labels: breaking-change, bump

#2291 Avoid futures SyntaxError
  molecule/shell.py
Labels: bump
