Repository ansible/molecule, pull requests merged in 2020-04, with the labels that each got.

#2632 Enable podman testing
  bindep.txt
  molecule/provisioner/ansible.py
  molecule/test/functional/conftest.py
  molecule/test/unit/provisioner/test_ansible.py
  setup.cfg
  tools/test-setup.sh
  zuul.d/layout.yaml
Labels: gate, podman

#2639 Implemented reset for docker driver
  molecule/command/reset.py
  molecule/driver/base.py
  molecule/driver/docker.py
  molecule/provisioner/ansible/playbooks/docker/create.yml
  molecule/test/scenarios/driver/docker/molecule/default/molecule.yml
Labels: docker, enhancement, gate

#2640 Correct typo in collection argument roles-file -> role-file
  molecule/dependency/ansible_galaxy/collections.py
  molecule/test/unit/dependency/ansible_galaxy/test_collections.py
  molecule/test/unit/dependency/ansible_galaxy/test_roles.py
Labels: bug, gate

#2642 Removed --driver-template option
  molecule/command/init/scenario.py
  molecule/test/functional/docker/test_scenarios.py
  molecule/test/unit/command/init/test_scenario.py
  zuul.d/layout.yaml
Labels: deprecated, gate

#2641 Mark some functional tests as extensive
  molecule/test/functional/test_command.py
  setup.cfg
  tox.ini
  zuul.d/layout.yaml
Labels: gate, skip-changelog, test

#2645 Add memory-swap to create docker driver
  molecule/provisioner/ansible/playbooks/docker/create.yml
  molecule/test/resources/playbooks/docker/create.yml
Labels: enhancement, gate

#2649 Issue #2466: Fix formatting issue in galaxy requirements-file code block.
  molecule/dependency/ansible_galaxy/__init__.py
Labels: docs, gate

#2644 Remove quick start stub and links from docs
  docs/getting-started.rst
  docs/index.rst
  docs/quick-start.rst
Labels: docs, gate

#2664 Fix docs building on Zuul
  bindep.txt
  tox.ini
  zuul.d/layout.yaml
Labels: docs, gate, skip-changelog, test

#2663 Improve dependencies
  bindep.txt
  setup.cfg
Labels: gate, packaging

#2661 docs: update python-libselinux to python3-libselinux EL8
  docs/installation.rst
Labels: gate

#2666 Allow drivers to overwrite template
  molecule/command/init/role.py
  molecule/command/init/scenario.py
Labels: enhancement, gate

#2679 Update pinned version for sh dependency
  setup.cfg
Labels: gate

#2680 Adds external plugins to the bundle dockerfile
  Dockerfile
Labels: gate
