Repository ansible/molecule, pull requests merged in 2020-07, with the labels that each got.

#2737 Add mol command alias
  README.rst
  molecule/test/unit/test_api.py
  setup.cfg
  zuul.d/layout.yaml
Labels: feature

#2742 Avoid failing tests due to docker deprecations
  setup.cfg
Labels: test

#2745 Correct ANSIBLE_COLLECTIONS_PATH
  molecule/config.py
  molecule/dependency/ansible_galaxy/collections.py
  molecule/provisioner/ansible.py
  molecule/shell.py
Labels: bug

#2748 Clear the APT package index files in default test images
  molecule/data/Dockerfile.j2
  molecule/test/resources/playbooks/docker/Dockerfile.j2
  molecule/test/resources/playbooks/podman/Dockerfile.j2
Labels: docker

#2746 Improve help text about base configuration loading
  molecule/shell.py
Labels: docs

#2749 Make container building more reliable
  Dockerfile
Labels: packaging

#2698 Hardened type checking
  .pre-commit-config.yaml
  molecule/api.py
  molecule/command/base.py
  molecule/command/init/init.py
  molecule/command/list.py
  molecule/driver/base.py
  molecule/logger.py
  molecule/shell.py
  molecule/status.py
  molecule/test/unit/test_status.py
  molecule/util.py
  mypy.ini
Labels: test

#2740 Test using Ansible 2.10 pre-releases
  tox.ini
Labels: skip-changelog, test

#2753 Remove custom callbacks from our tests
  molecule/test/scenarios/cleanup/molecule/default/molecule.yml
  molecule/test/scenarios/dependency/molecule/ansible-galaxy/molecule.yml
  molecule/test/scenarios/dependency/molecule/gilt/molecule.yml
  molecule/test/scenarios/dependency/molecule/shell/molecule.yml
  molecule/test/scenarios/driver/docker/molecule/default/molecule.yml
  molecule/test/scenarios/driver/docker/molecule/multi-node/molecule.yml
  molecule/test/scenarios/driver/podman/molecule/default/molecule.yml
  molecule/test/scenarios/driver/podman/molecule/multi-node/molecule.yml
  molecule/test/scenarios/host_group_vars/molecule/default/molecule.yml
  molecule/test/scenarios/host_group_vars/molecule/links/molecule.yml
  molecule/test/scenarios/idempotence/molecule/raises/molecule.yml
  molecule/test/scenarios/interpolation/molecule/default/molecule.yml
  molecule/test/scenarios/overrride_driver/molecule/default/molecule.yml
  molecule/test/scenarios/plugins/molecule/default/molecule.yml
  molecule/test/scenarios/side_effect/molecule/default/molecule.yml
  molecule/test/scenarios/test_destroy_strategy/molecule/default/molecule.yml
  molecule/test/scenarios/verifier/molecule/testinfra/molecule.yml
Labels: test

#2760 Fix minor typo on examples.rst
  docs/examples.rst
Labels: docs

#2762 Document needed tweaks for podman-in-docker
  docs/examples.rst
Labels: docs

#2767 Add -f alias for --force on prepare command
  molecule/command/prepare.py
Labels: enhancement
