Repository ansible/molecule, pull requests merged in 2020-10, with the labels that each got.

#2849 Fixed CustomLogger super call
  .github/workflows/tox.yml
  molecule/logger.py
  molecule/test/unit/test_logger.py
Labels: bug

#2869 Removed molecule ansible filters
  molecule/constants.py
  molecule/cookiecutter/scenario/driver/delegated/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/delegated/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/provisioner/ansible.py
  molecule/provisioner/ansible/plugins/filter/molecule_core.py
  molecule/test/unit/test_util.py
  molecule/util.py
Labels: major

#2868 export DEBIAN_FRONTEND when building image
  molecule/data/Dockerfile.j2
Labels: bug

#2873 Enable py39 support
  .github/workflows/tox.yml
  setup.cfg
  tox.ini
Labels: feature

#2874 Assure right labels are set before merge
  .github/workflows/readiness.yml
Labels: hacktoberfest-accepted, skip-changelog

#2875 Assured dependency installed collections are isolated
  molecule/dependency/base.py
  molecule/dependency/shell.py
  molecule/provisioner/ansible.py
  molecule/test/functional/test_command.py
  molecule/test/scenarios/dependency/molecule/ansible-galaxy/converge.yml
  molecule/test/scenarios/dependency/molecule/ansible-galaxy/requirements.yml
  molecule/test/scenarios/dependency/molecule/shell/converge.yml
  molecule/test/scenarios/dependency/molecule/shell/molecule.yml
  molecule/test/scenarios/dependency/molecule/shell/requirements.yml
  molecule/test/scenarios/dependency/molecule/shell/run.bash
Labels: bug

#2877 Assures we test role installation with dependency
  molecule/test/scenarios/dependency/molecule/ansible-galaxy/converge.yml
  molecule/test/scenarios/dependency/molecule/ansible-galaxy/molecule.yml
  molecule/test/scenarios/dependency/molecule/ansible-galaxy/requirements.yml
  molecule/test/scenarios/dependency/molecule/shell/converge.yml
  molecule/test/scenarios/dependency/molecule/shell/molecule.yml
Labels: hacktoberfest-accepted, skip-changelog

#2879 Allow external drivers to have their own embedded playbooks
  molecule/provisioner/ansible_playbooks.py
  molecule/test/unit/provisioner/test_ansible_playbooks.py
Labels: bug

#2881 Removed ansible plugin testing support
  molecule/test/resources/roles/testplugin/LICENSE
  molecule/test/resources/roles/testplugin/README.md
  molecule/test/resources/roles/testplugin/library/library.py
  molecule/test/resources/roles/testplugin/plugins/filters/core.py
  molecule/test/scenarios/plugins/library/project_library.py
  molecule/test/scenarios/plugins/meta/main.yml
  molecule/test/scenarios/plugins/molecule/default/converge.yml
  molecule/test/scenarios/plugins/molecule/default/molecule.yml
  molecule/test/scenarios/plugins/plugins/filters/project.py
  molecule/test/scenarios/plugins/tasks/main.yml
Labels: deprecated, test

#2882 Finalize Ansible python package dependency decoupling
  docs/installation.rst
  molecule/config.py
  molecule/constants.py
  molecule/shell.py
  molecule/test/functional/conftest.py
  setup.cfg
Labels: docs, major

#2886 Bump linters
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  tox.ini
Labels: skip-changelog, test

#2888 Relaxed test extra dependencies
  setup.cfg
Labels: bug

#2890 Added pytest-molecule install to devel jobs
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog, test

#2889 Contributing docs edit regarding broken URLs
  docs/contributing.rst
Labels: docs

#2897 Avoid implicit gather_facts on verify
  molecule/cookiecutter/scenario/verifier/ansible/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/verify.yml
Labels: bug

#2858 Documentation: fixing --parallel flag position and typos
  docs/ci.rst
  docs/examples.rst
  molecule/command/check.py
  molecule/command/destroy.py
  molecule/command/test.py
Labels: docs, enhancement

#2898 Added ansible-lint to test extras
  setup.cfg
Labels: skip-changelog, test

#2900 Include driver information alongside version
  lib/molecule/driver/base.py
  lib/molecule/shell.py
  setup.cfg
Labels: enhancement

#2901 Disable label check with target
  .github/workflows/readiness.yml
Labels: skip-changelog

#2904 Avoid using broken pip 2020-resolver
  .github/workflows/tox.yml
  Dockerfile
Labels: bug

#2903 Reflect changes in the molecule core in the documentation
  docs/installation.rst
Labels: docs

#2907 Avoid building molecule container with version 0.0.0
  Dockerfile
Labels: bug

#2908 Remove hetznerdriver from container
  Dockerfile
Labels: bug

#2906 Replace tabulate with rich
  .pre-commit-config.yaml
  .yamllint
  Dockerfile
  lib/molecule/command/drivers.py
  lib/molecule/command/list.py
  lib/molecule/console.py
  lib/molecule/driver/base.py
  pyproject.toml
  setup.cfg
Labels: enhancement

#2909 Remove readiness workflows
  .github/workflows/readiness.yml
  .gitignore
Labels: skip-changelog

#2910 Run pip check at the end of container building
  Dockerfile
Labels: bug

#2913 Remove coverage ceiling from test extra
  setup.cfg
Labels: bug

#2915 Add description of environment variables
  docs/configuration.rst
Labels: docs

#2914 Disable Ansible interpreter warnings
  lib/molecule/provisioner/ansible.py
  lib/molecule/test/unit/provisioner/test_ansible.py
Labels: enhancement, help wanted

#2918 Fixed plain formatting on scenario list
  .gitignore
  lib/molecule/command/list.py
  lib/molecule/test/functional/test_command.py
Labels: bug

#2917 Remove dependency on sh library
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  .yamllint
  lib/molecule/constants.py
  lib/molecule/dependency/ansible_galaxy/base.py
  lib/molecule/dependency/base.py
  lib/molecule/dependency/shell.py
  lib/molecule/provisioner/ansible_playbook.py
  lib/molecule/test/conftest.py
  lib/molecule/test/functional/conftest.py
  lib/molecule/test/functional/test_command.py
  lib/molecule/test/unit/command/test_base.py
  lib/molecule/test/unit/conftest.py
  lib/molecule/test/unit/cookiecutter/test_molecule.py
  lib/molecule/test/unit/dependency/ansible_galaxy/test_collections.py
  lib/molecule/test/unit/dependency/ansible_galaxy/test_roles.py
  lib/molecule/test/unit/dependency/test_shell.py
  lib/molecule/test/unit/provisioner/test_ansible_playbook.py
  lib/molecule/test/unit/test_api.py
  lib/molecule/test/unit/test_util.py
  lib/molecule/test/unit/verifier/test_testinfra.py
  lib/molecule/util.py
  lib/molecule/verifier/testinfra.py
  mypy.ini
  setup.cfg
Labels: major

#2920 Remove dependency on tree-format
  lib/molecule/scenarios.py
  lib/molecule/test/unit/test_scenarios.py
  lib/molecule/util.py
  setup.cfg
Labels: enhancement

#2922 Correct gitignore
  .gitignore
Labels: skip-changelog

#2921 Move pexpect from a runtime dependency to test
  Dockerfile
  lib/molecule/command/login.py
  setup.cfg
Labels: enhancement

#2924 Add ecosystem check tox env
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog, test

#2925 Removed run_command test helper
  lib/molecule/test/conftest.py
  lib/molecule/test/functional/conftest.py
  lib/molecule/test/functional/test_command.py
  lib/molecule/test/unit/cookiecutter/test_molecule.py
Labels: bug

#2926 Harden smoketest to avoid ansible becoming a python dependency
  tools/smoketest.sh
  tox.ini
Labels: test

#2928 Removed use of colorama from debug printing
  lib/molecule/test/unit/test_util.py
  lib/molecule/util.py
Labels: enhancement

#2930 Avoid duplicate stdout on playbook failures
  lib/molecule/provisioner/ansible_playbook.py
  lib/molecule/test/unit/provisioner/test_ansible_playbook.py
Labels: bug

#2929 Replace internal logger with rich logger
  .github/workflows/tox.yml
  lib/molecule/logger.py
  lib/molecule/shell.py
  lib/molecule/test/unit/test_logger.py
  mypy.ini
  setup.cfg
Labels: major

#2932 Improve coloring control
  lib/molecule/console.py
  lib/molecule/logger.py
  lib/molecule/test/unit/test_logger.py
Labels: enhancement

#2933 Add verbosity argument
  docs/configuration.rst
  lib/molecule/config.py
  lib/molecule/shell.py
Labels: feature

#2935 Remove molecule container building from core
  .github/workflows/tox.yml
  Dockerfile
  docs/contributing.rst
  docs/examples.rst
  tools/build-containers.py
  tox.ini
Labels: major

#2934 Display scenario and action on a single log line
  lib/molecule/command/base.py
  lib/molecule/console.py
  lib/molecule/test/unit/command/test_base.py
  lib/molecule/test/unit/command/test_check.py
  lib/molecule/test/unit/command/test_cleanup.py
  lib/molecule/test/unit/command/test_converge.py
  lib/molecule/test/unit/command/test_create.py
  lib/molecule/test/unit/command/test_dependency.py
  lib/molecule/test/unit/command/test_destroy.py
  lib/molecule/test/unit/command/test_idempotence.py
  lib/molecule/test/unit/command/test_lint.py
  lib/molecule/test/unit/command/test_prepare.py
  lib/molecule/test/unit/command/test_side_effect.py
  lib/molecule/test/unit/command/test_syntax.py
  lib/molecule/test/unit/command/test_verify.py
Labels: enhancement

#2936 Log matrix sequence as a single line
  lib/molecule/command/base.py
  lib/molecule/scenarios.py
Labels: enhancement

#2937 Make use of internal run_command
  lib/molecule/command/init/role.py
  lib/molecule/command/lint.py
  lib/molecule/config.py
  lib/molecule/util.py
Labels: enhancement

#2938 Improved styling of logging
  lib/molecule/console.py
Labels: enhancement

#2939 Remove debug message about schema validation
  lib/molecule/config.py
  lib/molecule/test/unit/test_config.py
Labels: enhancement
