Repository ansible/molecule, pull requests merged in 2020-09, with the labels that each got.

#2789 Replace Zuul CI with Github Actions
  .github/workflows/tox.yml
  .gitignore
  docs/configuration.rst
  molecule/data/validate-dockerfile.yml
  molecule/test/unit/driver/test_delegated.py
  molecule/test/unit/model/v2/conftest.py
  molecule/test/unit/provisioner/test_ansible_playbooks.py
  setup.cfg
  tools/build-containers.py
  tox.ini
  zuul.d/layout.yaml
Labels: skip-changelog

#2812 Remove podman driver from core
  bindep.txt
  docs/configuration.rst
  molecule/cookiecutter/scenario/driver/podman/cookiecutter.json
  molecule/cookiecutter/scenario/driver/podman/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/podman/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/converge.yml
  molecule/driver/podman.py
  molecule/model/schema_v3.py
  molecule/provisioner/ansible/playbooks/podman/create.yml
  molecule/provisioner/ansible/playbooks/podman/destroy.yml
  molecule/test/functional/conftest.py
  molecule/test/functional/test_command.py
  molecule/test/scenarios/driver/podman/molecule/ansible-verifier/converge.yml
  molecule/test/scenarios/driver/podman/molecule/default/converge.yml
  molecule/test/scenarios/driver/podman/molecule/default/molecule.yml
  molecule/test/scenarios/driver/podman/molecule/default/verify.yml
  molecule/test/scenarios/driver/podman/molecule/multi-node/converge.yml
  molecule/test/scenarios/driver/podman/molecule/multi-node/molecule.yml
  molecule/test/scenarios/driver/podman/molecule/multi-node/tests/__init__.py
  molecule/test/scenarios/driver/podman/molecule/multi-node/tests/test_bar.py
  molecule/test/scenarios/driver/podman/molecule/multi-node/tests/test_baz.py
  molecule/test/scenarios/driver/podman/molecule/multi-node/tests/test_default.py
  molecule/test/scenarios/driver/podman/molecule/multi-node/tests/test_foo.py
  setup.cfg
Labels: major

#2813 Remove test dependency on external galaxy role
  molecule/test/functional/test_command.py
  molecule/test/scenarios/dependency/molecule/ansible-galaxy/requirements.yml
  molecule/test/scenarios/dependency/molecule/shell/requirements.yml
Labels: test

#2814 Removed support for gilt
  .github/workflows/tox.yml
  docs/configuration.rst
  molecule/config.py
  molecule/dependency/gilt.py
  molecule/dependency/shell.py
  molecule/model/schema_v3.py
  molecule/test/functional/test_command.py
  molecule/test/scenarios/dependency/molecule/gilt/converge.yml
  molecule/test/scenarios/dependency/molecule/gilt/gilt.yml
  molecule/test/scenarios/dependency/molecule/gilt/molecule.yml
  molecule/test/scenarios/plugins/molecule/default/molecule.yml
  molecule/test/unit/dependency/test_gilt.py
  molecule/test/unit/model/v2/test_dependency_section.py
  molecule/test/unit/test_config.py
  setup.cfg
Labels: major

#2816 Prepare for 3.1.0
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.rst
  Dockerfile
  README.rst
  setup.cfg
Labels: major

#2638 Avoid parallel execution of a specific schenario
  .pre-commit-config.yaml
  molecule/constants.py
  molecule/scenario.py
Labels: feature

#2819 Include build-containers in CI/CD
  .github/workflows/tox.yml
  tools/build-containers.py
  tox.ini
Labels: skip-changelog

#2821 Correct GitHub Actions example
  docs/ci.rst
Labels: docs

#2824 Enforce use of newer pip resolver
  Dockerfile
  tox.ini
Labels: skip-changelog

#2826 Correct docstring for init role command class
  molecule/command/init/role.py
Labels: docs

#2829 Include filename with validation failures
  molecule/config.py
  molecule/test/unit/test_config.py
Labels: enhancement

#2830 Update ci.rst
  docs/ci.rst
Labels: docs

#2852 Fixed build-containers
  Dockerfile
Labels: bug

#2846 Sort tests files for testinfra by filename
  molecule/verifier/testinfra.py
Labels: bug

#2850 Remove unnecessary commands in ci docs
  docs/ci.rst
Labels: docs

#2847 Avoid importlib-metadata conflict with tox
  tox.ini
Labels: skip-changelog

#2848 Update molecule tag in examples.rst
  docs/examples.rst
Labels: docs
