Repository ansible/molecule, pull requests merged in 2020-03, with the labels that each got.

#2601 Fix dependency on pre-commit
  setup.cfg
Labels: gate, packaging

#2603 Fix container build
  Dockerfile
Labels: gate, packaging

#2604 Add missing spaces in gitlab-ci example
  docs/ci.rst
Labels: docs, gate

#2606 Fix a missing ":" before the reference to "galaxy".
  docs/getting-started.rst
Labels: docs, gate

#2602 Add snapcraft.io config
  .gitignore
  Dockerfile
  bindep.txt
  playbooks/snap-pre-run.yaml
  setup.cfg
  snap/snapcraft.yaml
  tox.ini
  zuul.d/layout.yaml
Labels: feature, gate

#2611 Fix removal of ANSI control characters when PY_COLORS=0
  molecule/logger.py
  molecule/test/unit/test_logger.py
Labels: bug, gate

#2612 Increase timeout on molecule-tox-packaging
  zuul.d/layout.yaml
Labels: gate

#2617 Adopt pytest-plus
  conftest.py
  setup.cfg
Labels: gate, skip-changelog

#2622 Make devel jobs non-voting
  zuul.d/layout.yaml
Labels: gate, skip-changelog

#2624 Avoid accidental skip of functional jobs
  zuul.d/layout.yaml
Labels: gate, skip-changelog

#2628 Make py36 minimal version needed for running molecule
  Dockerfile
  docs/ci.rst
  docs/installation.rst
  molecule/api.py
  molecule/command/base.py
  molecule/command/init/role.py
  molecule/command/lint.py
  molecule/config.py
  molecule/scenario.py
  molecule/test/functional/conftest.py
  molecule/test/unit/conftest.py
  molecule/util.py
  setup.cfg
  tools/test-setup.sh
  zuul.d/layout.yaml
Labels: critical, gate, major

#2627 Update Gitlab CI example
  docs/ci.rst
Labels: docs, gate

#2618 Avoid unreliable coverage versions
  setup.cfg
Labels: gate, skip-changelog, test

#2615 Add support for memory and kernel_memory module parameters
  molecule/provisioner/ansible/playbooks/docker/create.yml
  molecule/test/resources/playbooks/docker/create.yml
Labels: docker, feature, gate

#2620 Ansible 2.10 compatibility changes
  molecule/driver/docker.py
  molecule/test/unit/driver/test_docker.py
  tox.ini
  zuul.d/layout.yaml
Labels: enhancement, gate

#2623 Avoid errors with delegated create and destroy templates
  molecule/cookiecutter/scenario/driver/delegated/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  molecule/cookiecutter/scenario/driver/delegated/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  molecule/provisioner/ansible_playbook.py
  molecule/provisioner/ansible_playbooks.py
Labels: bug, gate

#2625 Fix Getting Started docs as default verifier is now Ansible not testinfra
  docs/getting-started.rst
Labels: docs, gate

#2609 Add support for collections as dependencies
  molecule/dependency/ansible_galaxy/__init__.py
  molecule/dependency/ansible_galaxy/base.py
  molecule/dependency/ansible_galaxy/collections.py
  molecule/dependency/ansible_galaxy/roles.py
  molecule/provisioner/ansible.py
  molecule/test/unit/dependency/ansible_galaxy/__init__.py
  molecule/test/unit/dependency/ansible_galaxy/test_collections.py
  molecule/test/unit/dependency/ansible_galaxy/test_roles.py
  zuul.d/layout.yaml
Labels: enhancement, gate

#2637 Fix nodeset for molecule-tox-py36-ubuntu-bionic
  zuul.d/layout.yaml
Labels: gate
