Repository ansible/molecule, pull requests merged in 2020-02, with the labels that each got.

#2520 Unpin pre-commit
  setup.cfg
Labels: gate

#2519 Make linters an optional dependency
  docs/installation.rst
  molecule/command/list.py
  setup.cfg
  tox.ini
Labels: gate, major

#2521 podman: fail tests with unsupported versions
  molecule/test/functional/conftest.py
Labels: gate, podman

#2522 Colorize command line help
  molecule/command/base.py
  molecule/command/check.py
  molecule/command/cleanup.py
  molecule/command/converge.py
  molecule/command/create.py
  molecule/command/dependency.py
  molecule/command/destroy.py
  molecule/command/drivers.py
  molecule/command/idempotence.py
  molecule/command/init/init.py
  molecule/command/init/role.py
  molecule/command/init/scenario.py
  molecule/command/lint.py
  molecule/command/list.py
  molecule/command/login.py
  molecule/command/matrix.py
  molecule/command/prepare.py
  molecule/command/side_effect.py
  molecule/command/syntax.py
  molecule/command/test.py
  molecule/command/verify.py
  molecule/shell.py
  setup.cfg
Labels: enhancement, gate

#2523 Remove redundant decode('utf-8') in tests
  molecule/test/functional/docker/test_scenarios.py
  molecule/util.py
Labels: gate, skip-changelist, test

#2525 Improve schema validation errors
  molecule/config.py
  molecule/model/schema_v2.py
  molecule/test/unit/model/v2/test_pre_validate.py
  molecule/test/unit/test_config.py
  molecule/util.py
Labels: .bump, enhancement, gate

#2524 Shell dependency: use proper lexical parsing
  CHANGELOG.rst
  molecule/dependency/shell.py
  molecule/test/unit/dependency/test_shell.py
  zuul.d/layout.yaml
Labels: bug, gate

#2526 Made init command required opts into args
  docs/getting-started.rst
  molecule/command/init/role.py
  molecule/command/init/scenario.py
  molecule/test/functional/conftest.py
  molecule/test/functional/docker/test_scenarios.py
Labels: .bump, enhancement, gate, major

#2527 Improve version information
  molecule/shell.py
Labels: enhancement, gate

#2529 Improve pytest collection failsafe
  tox.ini
Labels: gate, skip-changelist, test

#2530 Add publish-to-pypi zuul template
  zuul.d/layout.yaml
Labels: gate, skip-changelist

#2532 Minor docs fixes
  README.rst
Labels: gate

#2533 Rename playbook.yml to converge.yml
  docs/ci.rst
  docs/examples.rst
  docs/getting-started.rst
  molecule/config.py
  molecule/cookiecutter/scenario/driver/delegated/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/converge.yml
  molecule/cookiecutter/scenario/driver/docker/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/converge.yml
  molecule/cookiecutter/scenario/driver/podman/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/converge.yml
  molecule/provisioner/ansible.py
  molecule/test/resources/custom_scenario_template/docker/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/converge.yml
  molecule/test/scenarios/cleanup/molecule/default/converge.yml
  molecule/test/scenarios/dependency/molecule/ansible-galaxy/converge.yml
  molecule/test/scenarios/dependency/molecule/gilt/converge.yml
  molecule/test/scenarios/dependency/molecule/shell/converge.yml
  molecule/test/scenarios/driver/delegated/molecule/default/converge.yml
  molecule/test/scenarios/driver/docker/molecule/ansible-verifier/converge.yml
  molecule/test/scenarios/driver/docker/molecule/default/converge.yml
  molecule/test/scenarios/driver/docker/molecule/multi-node/converge.yml
  molecule/test/scenarios/driver/podman/molecule/ansible-verifier/converge.yml
  molecule/test/scenarios/driver/podman/molecule/default/converge.yml
  molecule/test/scenarios/driver/podman/molecule/multi-node/converge.yml
  molecule/test/scenarios/host_group_vars/molecule/default/converge.yml
  molecule/test/scenarios/host_group_vars/molecule/links/converge.yml
  molecule/test/scenarios/idempotence/molecule/raises/converge.yml
  molecule/test/scenarios/interpolation/molecule/default/converge.yml
  molecule/test/scenarios/overrride_driver/molecule/default/converge.yml
  molecule/test/scenarios/plugins/molecule/default/converge.yml
  molecule/test/scenarios/side_effect/molecule/default/converge.yml
  molecule/test/scenarios/test_destroy_strategy/molecule/default/converge.yml
  molecule/test/scenarios/verifier/molecule/testinfra-pre-commit/converge.yml
  molecule/test/scenarios/verifier/molecule/testinfra/converge.yml
  molecule/test/unit/provisioner/test_ansible.py
  molecule/test/unit/provisioner/test_ansible_playbooks.py
Labels: deprecated, gate

#2536 Makes pytest failures more verbose
  tox.ini
Labels: gate, skip-changelist, test

#2534 Makes ansible default verifier
  molecule/command/init/role.py
  molecule/command/init/scenario.py
  molecule/command/verify.py
  molecule/config.py
  molecule/test/functional/test_command.py
  molecule/test/resources/molecule_docker.yml
  molecule/test/scenarios/cleanup/molecule/default/molecule.yml
  molecule/test/scenarios/dependency/molecule/ansible-galaxy/molecule.yml
  molecule/test/scenarios/dependency/molecule/gilt/molecule.yml
  molecule/test/scenarios/dependency/molecule/shell/molecule.yml
  molecule/test/scenarios/driver/docker/molecule/ansible-verifier/molecule.yml
  molecule/test/scenarios/driver/docker/molecule/default/molecule.yml
  molecule/test/scenarios/driver/docker/molecule/default/tests/test_default.py
  molecule/test/scenarios/driver/docker/molecule/default/verify.yml
  molecule/test/scenarios/driver/docker/molecule/multi-node/molecule.yml
  molecule/test/scenarios/driver/docker/molecule/multi-node/tests/__init__.py
  molecule/test/scenarios/driver/docker/molecule/multi-node/tests/test_bar.py
  molecule/test/scenarios/driver/docker/molecule/multi-node/tests/test_baz.py
  molecule/test/scenarios/driver/docker/molecule/multi-node/tests/test_default.py
  molecule/test/scenarios/driver/docker/molecule/multi-node/tests/test_foo.py
  molecule/test/scenarios/driver/podman/molecule/ansible-verifier/molecule.yml
  molecule/test/scenarios/driver/podman/molecule/default/molecule.yml
  molecule/test/scenarios/driver/podman/molecule/default/tests/test_default.py
  molecule/test/scenarios/driver/podman/molecule/default/verify.yml
  molecule/test/scenarios/driver/podman/molecule/multi-node/molecule.yml
  molecule/test/scenarios/host_group_vars/molecule/default/molecule.yml
  molecule/test/scenarios/idempotence/molecule/raises/molecule.yml
  molecule/test/scenarios/interpolation/molecule/default/molecule.yml
  molecule/test/scenarios/overrride_driver/molecule/default/molecule.yml
  molecule/test/scenarios/plugins/molecule/default/molecule.yml
  molecule/test/scenarios/side_effect/molecule/default/molecule.yml
  molecule/test/scenarios/test_destroy_strategy/molecule/default/molecule.yml
  molecule/test/unit/command/init/test_role.py
  molecule/test/unit/command/init/test_scenario.py
  molecule/test/unit/command/test_verify.py
  molecule/test/unit/conftest.py
  molecule/test/unit/cookiecutter/test_molecule.py
  molecule/test/unit/test_config.py
  molecule/test/unit/test_interpolation.py
  molecule/test/unit/verifier/test_ansible.py
  molecule/verifier/ansible.py
  molecule/verifier/base.py
  molecule/verifier/testinfra.py
  setup.cfg
  zuul.d/layout.yaml
Labels: gate, major

#2542 Fix converge to playbook rename fallback logic
  molecule/command/verify.py
  molecule/provisioner/ansible.py
Labels: bug, gate

#2546 Add missing dependencies to docker image
  Dockerfile
Labels: gate

#2547 Mention container_default_behavior value
  molecule/provisioner/ansible/playbooks/docker/create.yml
  molecule/provisioner/ansible/playbooks/docker/destroy.yml
  molecule/test/resources/playbooks/delegated/create/docker.yml
  molecule/test/resources/playbooks/delegated/destroy/docker.yml
  molecule/test/resources/playbooks/docker/create.yml
  molecule/test/resources/playbooks/docker/destroy.yml
Labels: gate

#2545 Assure verify step is not skipped with testinfra
  molecule/command/verify.py
  molecule/provisioner/ansible.py
  molecule/test/unit/provisioner/test_ansible.py
  setup.cfg
Labels: bug, critical, gate

#2553 Replace logging.warn with warning
  molecule/command/cleanup.py
  molecule/command/create.py
  molecule/command/destroy.py
  molecule/command/init/scenario.py
  molecule/command/prepare.py
  molecule/command/side_effect.py
  molecule/dependency/ansible_galaxy.py
  molecule/dependency/gilt.py
  molecule/dependency/shell.py
  molecule/test/unit/command/test_cleanup.py
  molecule/test/unit/command/test_create.py
  molecule/test/unit/command/test_destroy.py
  molecule/test/unit/command/test_prepare.py
  molecule/test/unit/command/test_side_effect.py
  molecule/test/unit/conftest.py
  molecule/test/unit/dependency/test_ansible_galaxy.py
  molecule/test/unit/dependency/test_gilt.py
  molecule/test/unit/dependency/test_shell.py
  molecule/test/unit/verifier/test_ansible.py
  molecule/test/unit/verifier/test_testinfra.py
  molecule/verifier/ansible.py
  molecule/verifier/testinfra.py
Labels: gate, skip-changelist

#2555 Avoid breaking pytest collection with testinfra
  molecule/cookiecutter/scenario/verifier/testinfra/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/{{cookiecutter.verifier_directory}}/conftest.py
  molecule/cookiecutter/scenario/verifier/testinfra/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/{{cookiecutter.verifier_directory}}/test_default.py
Labels: bug, gate

#2554 Fixes playbook to converge rename regressions
  molecule/provisioner/ansible.py
  molecule/provisioner/ansible_playbooks.py
Labels: bug, critical, gate

#2556 Remove scenario name from molecule.yml
  molecule/model/schema_v3.py
  molecule/scenario.py
  molecule/test/scenarios/cleanup/molecule/default/molecule.yml
  molecule/test/scenarios/driver/delegated/molecule/default/molecule.yml
  molecule/test/scenarios/driver/docker/molecule/default/molecule.yml
  molecule/test/scenarios/driver/podman/molecule/default/molecule.yml
  molecule/test/scenarios/host_group_vars/molecule/default/molecule.yml
  molecule/test/scenarios/interpolation/molecule/default/molecule.yml
  molecule/test/scenarios/overrride_driver/molecule/default/molecule.yml
  molecule/test/scenarios/plugins/molecule/default/molecule.yml
  molecule/test/scenarios/side_effect/molecule/default/molecule.yml
  molecule/test/scenarios/test_destroy_strategy/molecule/default/molecule.yml
  molecule/test/unit/model/v2/test_pre_validate.py
  molecule/test/unit/model/v2/test_scenario_section.py
  molecule/test/unit/test_interpolation.py
Labels: feature, gate, major

#2558 Improve zuul job execution time
  zuul.d/layout.yaml
Labels: gate, skip-changelist, test

#2559 Corrects playbook.yml deprecation message
  molecule/provisioner/ansible_playbooks.py
Labels: bug, gate

#2561 Improve new issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/question.md
Labels: gate, skip-changelog

#2562 Update changelog for 3.0 release
  CHANGELOG.rst
  docs/installation.rst
Labels: docs, gate

#2566 Load molecule config from VCS if possible
  .config/molecule/config.yml
  molecule/shell.py
  molecule/util.py
Labels: feature, gate

#2567 Fixed link to releases in setup.cfg
  setup.cfg
Labels: gate, packaging

#2572 Extend driver api
  molecule/driver/base.py
  molecule/provisioner/ansible.py
  molecule/provisioner/ansible_playbooks.py
  molecule/test/unit/provisioner/test_ansible.py
Labels: enhancement, gate

#2571 Avoid loading all scenarios if not needed
  molecule/command/base.py
  molecule/test/unit/command/test_base.py
Labels: feature, gate

#2575 `set -e` for Lint Example
  docs/configuration.rst
Labels: docs, gate

#2573 Avoid ssh connection warnings
  molecule/driver/base.py
  molecule/test/unit/driver/test_delegated.py
Labels: enhancement, gate

#2576 Made packaging zuul job reusable
  zuul.d/layout.yaml
Labels: gate, skip-changelog

#2579 Ensure testinfra is installed in Docker image
  Dockerfile
Labels: gate

#2584 Install rsync in Docker Image
  Dockerfile
Labels: bug, gate, packaging

#2578 Suggest using python3 and pip3 in example docs
  Dockerfile
  README.rst
  docs/ci.rst
  docs/installation.rst
  docs/testing.rst
  molecule/command/lint.py
  molecule/cookiecutter/scenario/driver/docker/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/cookiecutter/scenario/driver/podman/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  molecule/driver/docker.py
  molecule/driver/podman.py
Labels: docs, gate

#2582 Inline RUN in Dockerfile to fix `apk` calls
  Dockerfile
Labels: bug, gate, packaging

#2577 Install Python 3 in non-RPM test images
  molecule/data/Dockerfile.j2
  molecule/test/resources/playbooks/docker/Dockerfile.j2
  molecule/test/resources/playbooks/podman/Dockerfile.j2
Labels: gate

#2592 Define reusable molecule jobs
  zuul.d/layout.yaml
Labels: gate, skip-changelog
