Repository ansible/molecule, pull requests merged in 2020-08, with the labels that each got.

#2775 Removed default provisioner lint configuration
  molecule/config.py
Labels: bug

#2768 Avoid abridged click output
  molecule/command/base.py
Labels: bug

#2770 Add environment dict to lint calls
  molecule/command/lint.py
Labels: bug

#2783 Assure env is passted to lint calls
  molecule/command/lint.py
  molecule/test/scenarios/driver/docker/molecule/default/molecule.yml
Labels: bug

#2791 Added mode to template #2785
  molecule/provisioner/ansible/playbooks/docker/create.yml
  molecule/provisioner/ansible/playbooks/podman/create.yml
Labels: bug

#2784 Avoid passenv=* with tox
  .ansible.cfg
  tox.ini
Labels: skip-changelog, test

#2795 Update docs to recommend docker:stable-dind
  docs/ci.rst
Labels: docs

#2794 Bump packaging requirements
  tox.ini
Labels: skip-changelog

#2798 Add driver-name parameter to init_scenario test helper
  molecule/test/functional/conftest.py
Labels: bug, test

#2802 Fixed linters
  .pre-commit-config.yaml
  molecule/command/lint.py
  molecule/driver/base.py
  molecule/provisioner/ansible.py
  molecule/scenarios.py
  molecule/shell.py
  molecule/test/functional/test_command.py
  molecule/test/unit/command/test_lint.py
Labels: bug

#2803 Update docs about .env.yml
  molecule/interpolation.py
Labels: docs

#2805 Remove dependency on ansible library
  molecule/config.py
  molecule/logger.py
  molecule/shell.py
  molecule/test/scenarios/plugins/library/project_library.py
  molecule/util.py
  setup.cfg
Labels: major

#2806 Enable pylint
  .pre-commit-config.yaml
  .pylintrc
  molecule/command/base.py
  molecule/dependency/base.py
  molecule/driver/base.py
  molecule/lint/base.py
  molecule/provisioner/base.py
  molecule/state.py
  molecule/test/conftest.py
  molecule/test/functional/conftest.py
  molecule/test/unit/cookiecutter/test_molecule.py
  molecule/verifier/base.py
Labels: skip-changelog

#2807 Removed multi-ansible version testing
  docs/contributing.rst
  tox.ini
  zuul.d/layout.yaml
Labels: skip-changelog, test

#2808 Serialize unit and functional testing
  setup.cfg
  tox.ini
  zuul.d/layout.yaml
Labels: skip-changelog, test
