Repository ansible/molecule, pull requests merged in 2020-11, with the labels that each got.

#2941 Documentation: Remove extra empty line in Drivers section
  docs/configuration.rst
Labels: docs

#2940 Fix indentation of example gitlab-ci configuration
  docs/ci.rst
Labels: docs

#2943 Fixed Manifest file
  .dockerignore
  .gitignore
  MANIFEST.in
  lib/molecule/py.typed
  tox.ini
Labels: bug

#2954 Prevent ansible from becoming a dependency
  setup.cfg
  tox.ini
Labels: bug

#2945 Use new testinfra package name
  .pre-commit-config.yaml
  setup.cfg
Labels: bug

#2927 Set ansible_ssh_pass with ansible_password because of a testinfra issue
  lib/molecule/driver/delegated.py
Labels: bug

#2956 Improve output when Ansible is missing
  lib/molecule/config.py
  lib/molecule/util.py
Labels: bug

#2958 Adds ability to produce html reports
  .pre-commit-config.yaml
  docs/configuration.rst
  lib/molecule/command/base.py
  lib/molecule/console.py
  lib/molecule/util.py
  setup.cfg
Labels: feature

#2964 Document toolset container
  docs/examples.rst
Labels: docs

#2962 Switch from inventory file to directory for testinfra call
  lib/molecule/driver/base.py
  lib/molecule/test/unit/driver/test_delegated.py
  lib/molecule/test/unit/verifier/test_testinfra.py
Labels: bug

#2966 Prevent Ansible args from leaking to create and destroy
  lib/molecule/provisioner/ansible_playbook.py
  lib/molecule/test/unit/provisioner/test_ansible_playbook.py
Labels: bug

#2969 Refactored text functions out of util module
  lib/molecule/command/idempotence.py
  lib/molecule/test/functional/conftest.py
  lib/molecule/test/unit/test_scenarios.py
  lib/molecule/test/unit/test_text.py
  lib/molecule/test/unit/test_util.py
  lib/molecule/text.py
  lib/molecule/util.py
Labels: major

#2972 Refreshed test dependencies
  setup.cfg
Labels: skip-changelog

#2975 Refactor execute to use wrapper for logging
  src/molecule/command/base.py
  src/molecule/command/check.py
  src/molecule/command/cleanup.py
  src/molecule/command/converge.py
  src/molecule/command/create.py
  src/molecule/command/dependency.py
  src/molecule/command/destroy.py
  src/molecule/command/idempotence.py
  src/molecule/command/lint.py
  src/molecule/command/prepare.py
  src/molecule/command/side_effect.py
  src/molecule/command/syntax.py
  src/molecule/command/verify.py
Labels: enhancement

#2977 Refactor version printing
  src/molecule/shell.py
Labels: enhancement

#2979 Fix click ANSI support regression
  src/molecule/command/base.py
Labels: bug

#2980 Consolidated use of rich console
  setup.cfg
  src/molecule/console.py
  src/molecule/logger.py
Labels: bug

#2981 Removed print_info from command base class
  .github/workflows/tox.yml
  src/molecule/command/base.py
  src/molecule/test/unit/command/test_base.py
Labels: deprecated

#2978 Removed custom logger
  src/molecule/command/idempotence.py
  src/molecule/command/init/role.py
  src/molecule/command/init/scenario.py
  src/molecule/dependency/ansible_galaxy/base.py
  src/molecule/dependency/base.py
  src/molecule/logger.py
  src/molecule/provisioner/ansible_playbook.py
  src/molecule/test/functional/conftest.py
  src/molecule/test/unit/command/init/test_role.py
  src/molecule/test/unit/command/init/test_scenario.py
  src/molecule/test/unit/command/test_idempotence.py
  src/molecule/test/unit/conftest.py
  src/molecule/test/unit/dependency/ansible_galaxy/test_collections.py
  src/molecule/test/unit/dependency/ansible_galaxy/test_roles.py
  src/molecule/test/unit/dependency/test_shell.py
  src/molecule/test/unit/test_config.py
  src/molecule/test/unit/verifier/test_ansible.py
  src/molecule/test/unit/verifier/test_testinfra.py
  src/molecule/verifier/ansible.py
  src/molecule/verifier/testinfra.py
Labels: deprecated

#2982 Assure we install dataclasses on py36
  setup.cfg
Labels: bug

#2983 Moved more text functions to text module
  src/molecule/command/base.py
  src/molecule/command/list.py
  src/molecule/test/unit/test_text.py
  src/molecule/test/unit/test_util.py
  src/molecule/text.py
  src/molecule/util.py
Labels: deprecated

#2984 Enable multiple section wrappers
  src/molecule/command/base.py
  src/molecule/logger.py
Labels: skip-changelog

#2985 Remove mock as a dependency
  setup.cfg
  src/molecule/test/unit/verifier/test_testinfra.py
Labels: bug

#2976 Display each command as a collapsable section under CI
  src/molecule/console.py
  src/molecule/logger.py
Labels: feature

#2986 docs/getting-started.rst: Add missing argument to init role
  docs/getting-started.rst
Labels: docs

#2989 Allow to set login_cmd_template for delegate driver
  src/molecule/driver/delegated.py
Labels: bug

#2987 Add tests for section_loggers
  .github/workflows/tox.yml
  src/molecule/test/unit/test_logger.py
Labels: enhancement

#2990 Improve ANSI coloring detection
  src/molecule/console.py
Labels: enhancement

#2991 Fix dumb terminal condition
  src/molecule/console.py
Labels: bug

#2988 Fix connection option handling for delegated driver
  src/molecule/driver/delegated.py
Labels: bug, needs-update

#2996 Assure provisioner logging is enabled by default
  src/molecule/config.py
Labels: bug

#3001 Acknowledge click 8.0 incompatibility
  setup.cfg
Labels: bug
