Repository ansible/molecule, pull requests merged in 2020-12, with the labels that each got.

#3002 Avoid misleading user about load of missing config
  mypy.ini
  src/molecule/util.py
Labels: bug

#3003 Increased type checking
  mypy.ini
  src/molecule/command/base.py
  src/molecule/command/init/scenario.py
  src/molecule/config.py
  src/molecule/interpolation.py
  src/molecule/model/schema_v3.py
  src/molecule/scenario.py
  src/molecule/test/unit/conftest.py
  src/molecule/util.py
Labels: skip-changelog, test

#3006 Avoid use of property decorator for project_directory
  src/molecule/config.py
Labels: bug

#3000 Refactor logging
  src/molecule/api.py
  src/molecule/command/base.py
  src/molecule/command/check.py
  src/molecule/command/cleanup.py
  src/molecule/command/converge.py
  src/molecule/command/create.py
  src/molecule/command/dependency.py
  src/molecule/command/destroy.py
  src/molecule/command/drivers.py
  src/molecule/command/idempotence.py
  src/molecule/command/init/base.py
  src/molecule/command/init/init.py
  src/molecule/command/init/role.py
  src/molecule/command/init/scenario.py
  src/molecule/command/lint.py
  src/molecule/command/list.py
  src/molecule/command/login.py
  src/molecule/command/matrix.py
  src/molecule/command/prepare.py
  src/molecule/command/reset.py
  src/molecule/command/side_effect.py
  src/molecule/command/syntax.py
  src/molecule/command/test.py
  src/molecule/command/verify.py
  src/molecule/config.py
  src/molecule/dependency/ansible_galaxy/base.py
  src/molecule/dependency/ansible_galaxy/collections.py
  src/molecule/dependency/ansible_galaxy/roles.py
  src/molecule/dependency/base.py
  src/molecule/dependency/shell.py
  src/molecule/driver/delegated.py
  src/molecule/logger.py
  src/molecule/platforms.py
  src/molecule/provisioner/ansible.py
  src/molecule/provisioner/ansible_playbook.py
  src/molecule/provisioner/ansible_playbooks.py
  src/molecule/scenario.py
  src/molecule/scenarios.py
  src/molecule/shell.py
  src/molecule/state.py
  src/molecule/test/conftest.py
  src/molecule/util.py
  src/molecule/verifier/ansible.py
  src/molecule/verifier/testinfra.py
Labels: enhancement

#3007 Extend run_command implementation
  setup.cfg
  src/molecule/util.py
Labels: enhancement

#3015 Narrow down dependency versions
  setup.cfg
Labels: bug

#3014 Avoid using lock unless parallel mode is present
  src/molecule/scenario.py
Labels: bug

#3011 Fix typos in docs
  docs/ci.rst
  docs/getting-started.rst
Labels: docs

#3013 Refactored use of console for logging
  .pre-commit-config.yaml
  setup.cfg
  src/molecule/logger.py
  src/molecule/shell.py
  src/molecule/util.py
Labels: bug

#3018 docs: fix simple typo, requres -> requires
  src/molecule/logger.py
Labels: skip-changelog
