Repository ansible/molecule, pull requests merged in 2021-01, with the labels that each got.

#3027 Add Hetzner Cloud plugin into testing again
  tox.ini
Labels: feature

#3026 Allow os_walk to follow symlinks
  src/molecule/util.py
  src/molecule/verifier/testinfra.py
Labels: bug

#3029 Support multiple base configs
  .github/workflows/tox.yml
  src/molecule/config.py
  src/molecule/shell.py
  src/molecule/test/unit/test_config.py
Labels: feature

#3040 Assure image is included for containers driver
  src/molecule/cookiecutter/molecule/{{cookiecutter.role_name}}/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/molecule.yml
Labels: enhancement
