Repository ansible/molecule, pull requests merged in 2021-06, with the labels that each got.

#3132 Switch from freenode to libera.chat
  README.rst
  docs/conf.py
  docs/contributing.rst
Labels: docs

#3128 Avoid using in-repo .cache folder
  .pre-commit-config.yaml
  setup.cfg
Labels: bug

#3141 Bump dependendencies
  setup.cfg
Labels: bug

#3142 Add missing workflows
  .github/workflows/labels.yml
  .github/workflows/release-drafter.yml
Labels: skip-changelog, test

#3143 Fix ansible version parsing
  .github/workflows/tox.yml
  src/molecule/config.py
  src/molecule/test/unit/test_config.py
Labels: bug

#3145 Uses discussions for new features
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/proposal.md
Labels: skip-changelog

#3168 Fix pip documentation link
  docs/installation.rst
Labels: bug, docs

#3167 Update release drafter config
  .github/release-drafter.yml
Labels: skip-changelog

#3166 ``molecule test`` add support of ansible args
  src/molecule/command/test.py
Labels: enhancement
