Repository ansible/molecule, pull requests merged in 2021-03, with the labels that each got.

#3061 Assure we install ansible on eco test
  tox.ini
Labels: skip-changelog

#3059 Document use of newer toolset container image
  .github/workflows/tox.yml
  docs/ci.rst
  docs/examples.rst
  docs/installation.rst
Labels: bug

#3056 Update ci.rst GitHub Actions Docker already installed
  docs/ci.rst
Labels: skip-changelog

#3068 Add ansible-core version string parsing
  .github/workflows/tox.yml
  src/molecule/config.py
  src/molecule/test/unit/test_config.py
Labels: bug

#3066 Update linter versions from lint extra
  setup.cfg
  tox.ini
Labels: enhancement

#3074 Update installation.rst
  docs/installation.rst
Labels: enhancement

#3078 Remove broken Debian ansible package from GHA
  .github/workflows/tox.yml
Labels: skip-changelog

#3079 Assure molecule uses root logger
  src/molecule/logger.py
Labels: bug

#3080 Enable codespell
  .pre-commit-config.yaml
  docs/examples.rst
  docs/index.rst
  docs/installation.rst
  src/molecule/command/base.py
  src/molecule/command/prepare.py
  src/molecule/driver/base.py
  src/molecule/provisioner/ansible.py
  src/molecule/test/unit/command/test_converge.py
  src/molecule/test/unit/model/v2/conftest.py
  src/molecule/verifier/base.py
Labels: skip-changelog

#3077 Make molecule reuse prerun from ansible-lint
  .config/molecule/config.yml
  .pre-commit-config.yaml
  .readthedocs.yml
  docs/configuration.rst
  mypy.ini
  setup.cfg
  src/molecule/command/base.py
  src/molecule/config.py
  src/molecule/data/validate-dockerfile.yml
  src/molecule/provisioner/ansible.py
  src/molecule/test/unit/provisioner/test_ansible.py
  tox.ini
Labels: enhancement

#3081 Adding Azure Pipelines CI Documentation
  docs/ci.rst
Labels: docs
