Repository ansible/molecule, pull requests merged in 2021-11, with the labels that each got.

#3290 Correct ansible version used by devel pipelines
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog

#3260 Add support for py310
  .github/workflows/tox.yml
  setup.cfg
  tox.ini
Labels: bug

#3293 Bump test dependencies
  .pre-commit-config.yaml
  constraints.txt
  tox.ini
Labels: skip-changelog

#3295 Deprecate ansible[-base] extras
  .github/workflows/tox.yml
  .readthedocs.yml
  docs/installation.rst
  setup.cfg
  tox.ini
Labels: deprecated

#3298 Enable doc8
  .pre-commit-config.yaml
  docs/ci.rst
  docs/configuration.rst
  docs/contributing.rst
  docs/examples.rst
  docs/getting-started.rst
  setup.cfg
  src/molecule/cookiecutter/scenario/driver/delegated/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
Labels: enhancement

#3300 docs(#3299): avoid to use dash for role name
  docs/getting-started.rst
Labels: bug, docs

#3303 Only test bash completion if bash version > 4.4
  src/molecule/test/unit/command/test_base.py
Labels: skip-changelog

#3310 Support PyYAML 6.0
  setup.cfg
Labels: enhancement

#3313 Ensure cwd is passed to utils.run_command() in all cases
  src/molecule/util.py
Labels: bug

#3277 Ensure roles have a namespace when created
  src/molecule/command/init/role.py
  src/molecule/test/unit/command/init/test_role.py
Labels: bug

#3315 Replace pep517.build with build
  tox.ini
Labels: skip-changelog

#3316 Workaround for tox w/o setup.py bug
  tox.ini
Labels: skip-changelog

#3317 Remove sudo from default alpine image
  src/molecule/data/Dockerfile.j2
  tox.ini
Labels: bug

#3178 Run functional tests in serial
  .pre-commit-config.yaml
  pyproject.toml
  setup.cfg
  src/molecule/test/conftest.py
  src/molecule/test/functional/test_command.py
  tox.ini
Labels: test, skip-changelog

#3321 Add missing filelock test dependency
  .pre-commit-config.yaml
  .pylintrc
  constraints.txt
  setup.cfg
  src/molecule/test/conftest.py
  src/molecule/test/unit/test_util.py
Labels: bug

#3320 Bump test deps
  constraints.txt
Labels: skip-changelog

#3324 Fix sdist file inclusion to just pack the Git-tracked files
  MANIFEST.in
  tox.ini
Labels: bug, skip-changelog, backport-3.4
