Repository ansible/molecule, pull requests merged in 2021-07, with the labels that each got.

#3162 Avoid None among plugin directories
  src/molecule/provisioner/ansible.py
  src/molecule/util.py
Labels: bug

#3170 Improve molecule init
  src/molecule/cookiecutter/scenario/driver/delegated/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  src/molecule/cookiecutter/scenario/driver/delegated/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
Labels: bug

#3172 Assure we also run functional tests
  .github/workflows/tox.yml
  src/molecule/test/functional/test_command.py
  tox.ini
Labels: bug

#3183 Update .pre-commit-config.yaml pylint repo
  .pre-commit-config.yaml
Labels: enhancement

#3191 Make init role testing use fully qualified role names
  src/molecule/test/functional/conftest.py
Labels: skip-changelog, test

#3194 Upgrade pylint
  .pre-commit-config.yaml
  src/molecule/api.py
  src/molecule/config.py
  src/molecule/dependency/ansible_galaxy/base.py
  src/molecule/dependency/base.py
  src/molecule/driver/base.py
  src/molecule/lint/base.py
  src/molecule/provisioner/base.py
  src/molecule/scenario.py
  src/molecule/test/unit/provisioner/test_ansible.py
  src/molecule/verifier/base.py
Labels: bug

#3195 Drop use of pytest-helpers-namespace
  conftest.py
  setup.cfg
  src/molecule/config.py
  src/molecule/test/conftest.py
  src/molecule/test/functional/conftest.py
  src/molecule/test/functional/test_command.py
  src/molecule/test/unit/conftest.py
  src/molecule/test/unit/provisioner/test_ansible.py
  src/molecule/test/unit/provisioner/test_ansible_playbooks.py
  src/molecule/test/unit/test_util.py
Labels: bug, major

#3193 Bump linters
  .pre-commit-config.yaml
  mypy.ini
  src/molecule/test/functional/test_command.py
  src/molecule/test/scenarios/cleanup/molecule/default/tests/test_cleanup.py
  src/molecule/test/scenarios/side_effect/molecule/default/tests/test_side_effect.py
  src/molecule/test/scenarios/test_destroy_strategy/molecule/default/tests/test_destroy_strategy.py
  src/molecule/test/scenarios/verifier/molecule/testinfra-pre-commit/tests/test_testinfra_pre_commit.py
  src/molecule/test/scenarios/verifier/molecule/testinfra/tests/test_testinfra.py
Labels: skip-changelog

#3196 Isolate release pipeline from testing one
  .github/workflows/release.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#3192 Allow molecule drivers to require collections
  setup.cfg
  src/molecule/dependency/ansible_galaxy/base.py
  src/molecule/dependency/base.py
  src/molecule/dependency/shell.py
  src/molecule/driver/base.py
  src/molecule/shell.py
Labels: feature

#3200 Bump jinja2 minimal version
  setup.cfg
Labels: enhancement
