Repository ansible/molecule, pull requests merged in 2021-12, with the labels that each got.

#3322 Drop testing of digitalocean, hetznercloud, lxd and openstack plugins
  tox.ini
Labels: bug

#3292 Adopt check pipeline job
  .github/workflows/tox.yml
Labels: skip-changelog

#3328 Provide implicit value for experimental flag
  .github/workflows/tox.yml
Labels: skip-changelog

#3333 fix docstring for Schema v3 Validation Module
  src/molecule/model/schema_v3.py
Labels: bug

#3329 Fix GHA check-gate to properly identify failures
  .github/workflows/tox.yml
Labels: bug, enhancement, critical, skip-changelog, backport-3.4, new

#3334 Clarify per-project config.yml file
  docs/configuration.rst
Labels: bug
