Repository ansible/molecule, pull requests merged in 2022-06, with the labels that each got.

#3565 Do not gather facts on newly created scenarios
  src/molecule/cookiecutter/scenario/driver/delegated/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/converge.yml
Labels: bug

#3225 Restore auto-installation of local collection
  .github/workflows/tox.yml
  src/molecule/test/functional/test_command.py
  src/molecule/test/resources/sample-collection/galaxy.yml
  src/molecule/test/resources/sample-collection/molecule/default/converge.yml
  src/molecule/test/resources/sample-collection/molecule/default/molecule.yml
  src/molecule/test/resources/sample-collection/roles/get_rich/tasks/main.yml
Labels: bug, needs-update

#3529 Add more tests related to Ansible runtime path modifications
  .github/workflows/tox.yml
  src/molecule/provisioner/ansible_playbook.py
  src/molecule/test/unit/command/test_base.py
Labels: skip-changelog

#3584 Bump test dependencies
  .pre-commit-config.yaml
Labels: skip-changelog

#3571 doc: update doc on inventory/host section for provisioner
  src/molecule/provisioner/ansible.py
Labels: bug

#3590 Bugfix test init role and scenario
  .github/workflows/tox.yml
  src/molecule/test/functional/conftest.py
  src/molecule/test/functional/test_command.py
Labels: skip-changelog

#3592 Enable molecule dependency test
  .github/workflows/tox.yml
  src/molecule/test/functional/test_command.py
  src/molecule/test/scenarios/dependency/molecule/ansible-galaxy/converge.yml
  src/molecule/test/scenarios/dependency/molecule/ansible-galaxy/molecule.yml
  src/molecule/test/scenarios/dependency/molecule/shell/converge.yml
Labels: skip-changelog

#3599 Avoid harassment from dependabot
  .github/dependabot.yml
Labels: skip-changelog

#3605 doc: add description for action arguments (verify and side_effect)
  src/molecule/scenario.py
Labels: bug, docs

#3600 Docs: fix undocumented env vars
  docs/configuration.rst
Labels: bug, docs
