Repository ansible/molecule, pull requests merged in 2022-12, with the labels that each got.

#3764 Fix running tox:dockerfile with docker secretservice enabled
  tox.ini
Labels: bug

#3730 Allow side_effect and verify to have parameters
  src/molecule/data/molecule.json
Labels: bug

#3734 Update build-system requirements for setuptools-scm to >=7.0.0
  pyproject.toml
Labels: skip-changelog

#3767 Adopt PEP-621 for packaging
  .config/molecule.spec
  .flake8
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  README.md
  README.rst
  docs/index.rst
  pyproject.toml
  requirements.txt
  setup.cfg
  tox.ini
Labels: enhancement
