Repository ansible/molecule, pull requests merged in 2022-03, with the labels that each got.

#3454 Remove paramiko dependency
  requirements.txt
  setup.cfg
  tox.ini
Labels: bug, AAP

#3457 Removed mol command line alias
  .github/workflows/tox.yml
  setup.cfg
  src/molecule/__main__.py
  src/molecule/test/unit/test_api.py
Labels: major, AAP

#3458 Remove mol command from documentation
  README.rst
Labels: skip-changelog

#3456 Enable packit rpm building for Fedora 35
  .config/molecule.spec
  .packit.yaml
  tools/get-version.sh
  tools/update-version.sh
Labels: enhancement, AAP

#3459 Fix additional_files_or_dirs in skip check
  src/molecule/verifier/testinfra.py
Labels: bug

#3429 Added state-file driver validation
  src/molecule/config.py
  src/molecule/test/unit/test_config.py
Labels: bug

#3468 fix broken molecule login
  src/molecule/command/login.py
Labels: bug

#3479 change IRC room from `ansible-molecule` to `ansible-devtools`
  README.rst
Labels: bug

#3476 Correct RTD config to install ansible-core
  .pre-commit-config.yaml
  .readthedocs.yml
  requirements.txt
  setup.cfg
Labels: skip-changelog

#3485 Upgrade sphinx
  requirements.txt
  setup.cfg
Labels: skip-changelog

#3491 Clean sphinx config
  .pre-commit-config.yaml
  docs/conf.py
Labels: skip-changelog
