Repository ansible/molecule, pull requests merged in 2022-09, with the labels that each got.

#3646 Downgrade log level when linking Ansible variables
  src/molecule/provisioner/ansible.py
Labels: bug

#3638 Replace cerberus with jsonschema for configuration validation
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  mypy.ini
  requirements.txt
  setup.cfg
  src/molecule/config.py
  src/molecule/model/schema_v3.py
  src/molecule/schemas/__init__.py
  src/molecule/schemas/molecule.json
  src/molecule/test/resources/molecule.yml
  src/molecule/test/unit/cookiecutter/test_molecule.py
  src/molecule/test/unit/model/v2/test_dependency_section.py
  src/molecule/test/unit/model/v2/test_driver_section.py
  src/molecule/test/unit/model/v2/test_platforms_section.py
  src/molecule/test/unit/model/v2/test_pre_validate.py
  src/molecule/test/unit/model/v2/test_provisioner_section.py
  src/molecule/test/unit/model/v2/test_scenario_section.py
  src/molecule/test/unit/model/v2/test_schema.py
  src/molecule/test/unit/model/v2/test_verifier_section.py
  src/molecule/test/unit/test_config.py
Labels: enhancement

#3650 Update test dependencies
  requirements.txt
Labels: skip-changelog

#3668 Adopt molecule config JSON schema
  .gitignore
  .pre-commit-config.yaml
  requirements.txt
  setup.cfg
  src/molecule/data/molecule.json
  tools/test-schema/.mocharc.json
  tools/test-schema/f/molecule.json
  tools/test-schema/negative_test/molecule/platforms_children/molecule.yml
  tools/test-schema/negative_test/molecule/platforms_children/molecule.yml.md
  tools/test-schema/negative_test/molecule/platforms_networks/molecule.yml
  tools/test-schema/negative_test/molecule/platforms_networks/molecule.yml.md
  tools/test-schema/package-lock.json
  tools/test-schema/package.json
  tools/test-schema/src/schema.spec.ts
  tools/test-schema/test/molecule/cluster/molecule.yml
  tools/test-schema/test/molecule/default/molecule.yml
  tools/test-schema/test/molecule/vagrant/molecule.yml
  tools/test-schema/tsconfig.json
  tox.ini
Labels: bug

#3671 Schema fix
  src/molecule/data/__init__.py
  src/molecule/data/molecule.json
  src/molecule/model/schema_v3.py
  src/molecule/schemas/__init__.py
  src/molecule/schemas/molecule.json
  src/molecule/test/unit/model/v2/test_dependency_section.py
Labels: bug
