Repository ansible/molecule, pull requests merged in 2022-04, with the labels that each got.

#3416 Add support for MOLECULE_PLATFORM_NAME
  .github/workflows/tox.yml
  docs/getting-started.rst
  src/molecule/command/test.py
  src/molecule/config.py
  src/molecule/platforms.py
  src/molecule/test/functional/test_command.py
  src/molecule/test/unit/test_platforms.py
  src/molecule/util.py
Labels: enhancement

#3508 Fix black dependency issue in pre-commit hook
  .pre-commit-config.yaml
  src/molecule/test/unit/test_scenarios.py
Labels: skip-changelog

#3499 Change ansible-lint version since version 6.0.0 and greater doesn't work
  .pre-commit-config.yaml
  setup.cfg
Labels: bug

#3505 bump gha actions/checkout to v2
  .github/workflows/tox.yml
Labels: test, skip-changelog

#3509 Workaround for RTD problem with jinja2
  requirements.txt
  setup.cfg
Labels: skip-changelog

#3510 Disable latex output
  .readthedocs.yml
  docs/conf.py
Labels: skip-changelog

#3516 Fix wrong environment variables being passed to ansible compat (#3404)
  src/molecule/provisioner/ansible_playbook.py
Labels: bug

#3521 Missing `f` prefix on f-strings fix
  src/molecule/scenarios.py
Labels: bug
