Repository ansible/molecule, pull requests merged in 2022-02, with the labels that each got.

#3431 Replace centos:8 with centos:stream8
  conftest.py
  docs/examples.rst
  src/molecule/cookiecutter/molecule/{{cookiecutter.role_name}}/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/molecule.yml
  src/molecule/data/Dockerfile.j2
  src/molecule/data/validate-dockerfile.yml
Labels: bug

#3407 Add deprecation warning for the `mol` command
  setup.cfg
  src/molecule/__main__.py
  src/molecule/test/unit/test_api.py
Labels: bug

#3432 Bump test dependencies
  requirements.txt
  tools/opts.txt
Labels: skip-changelog

#3409 Fix prepare_environment call for role installs
  src/molecule/command/base.py
  src/molecule/test/functional/test_command.py
  src/molecule/test/scenarios/driver/delegated/meta/main.yml
Labels: bug

#3436 Remove support for py36 and py37
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  .readthedocs.yml
  docs/ci.rst
  docs/installation.rst
  mypy.ini
  requirements.txt
  runtime.txt
  setup.cfg
  src/molecule/__init__.py
  tox.ini
Labels: skip-changelog

#3450 Remove python versions from tox envlist
  tox.ini
Labels: skip-changelog

#3395 Remove `ansible` and `ansible-base` extras
  docs/installation.rst
  setup.cfg
Labels: enhancement, major, AAP

#3452 Bump test dependencies
  requirements.txt
Labels: skip-changelog

#3446 docs: ansible-lint is not a molecule dep
  docs/configuration.rst
  docs/getting-started.rst
  docs/installation.rst
  setup.cfg
  src/molecule/command/init/scenario.py
Labels: bug
