Repository ansible/molecule, pull requests merged in 2022-10, with the labels that each got.

#3680 Use FQCN at any point I found
  docs/getting-started.rst
  playbooks/snap-pre-run.yaml
  src/molecule/data/validate-dockerfile.yml
  src/molecule/test/resources/playbooks/delegated/create.yml
  src/molecule/test/resources/playbooks/delegated/destroy.yml
  src/molecule/test/resources/roles/molecule/tasks/main.yml
  src/molecule/test/resources/sample-collection/molecule/default/converge.yml
  src/molecule/test/resources/sample-collection/roles/get_rich/tasks/main.yml
  src/molecule/test/scenarios/cleanup/molecule/default/cleanup.yml
  src/molecule/test/scenarios/cleanup/molecule/default/converge.yml
  src/molecule/test/scenarios/dependency/molecule/ansible-galaxy/converge.yml
  src/molecule/test/scenarios/host_group_vars/molecule/default/converge.yml
  src/molecule/test/scenarios/host_group_vars/molecule/links/converge.yml
  src/molecule/test/scenarios/idempotence/tasks/main.yml
  src/molecule/test/scenarios/interpolation/molecule/default/converge.yml
  src/molecule/test/scenarios/overrride_driver/molecule/default/converge.yml
  src/molecule/test/scenarios/side_effect/molecule/default/converge.yml
  src/molecule/test/scenarios/side_effect/molecule/default/side_effect.yml
  src/molecule/test/scenarios/test_destroy_strategy/molecule/default/converge.yml
  src/molecule/test/scenarios/verifier/molecule/testinfra-pre-commit/converge.yml
Labels: bug

#3681 Support ANSIBLE_COLLECTIONS_PATH environment var
  src/molecule/provisioner/ansible.py
Labels: feature

#3690 Platform `env` expects a dict of vars
  src/molecule/data/molecule.json
  tools/test-schema/test/molecule/cluster/molecule.yml
Labels: bug

#3700 Add support for cgroupns_mode
  src/molecule/data/molecule.json
  tools/test-schema/test/molecule/cluster/molecule.yml
Labels: bug

#3709 Update test dependencies
  pyproject.toml
  requirements.txt
Labels: skip-changelog

#3706 Re-add credentials to Docker registry schema
  src/molecule/data/molecule.json
Labels: bug
