Repository ansible/molecule, pull requests merged in 2023-07, with the labels that each got.

#3951 Move mypy config to pyproject.toml
  .pre-commit-config.yaml
  mypy.ini
  pyproject.toml
Labels: skip-changelog

#3952 Add more types
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  pyproject.toml
  src/molecule/command/converge.py
  src/molecule/config.py
  src/molecule/driver/base.py
  src/molecule/test/a_unit/command/test_base.py
  src/molecule/test/a_unit/command/test_converge.py
  src/molecule/test/a_unit/conftest.py
  src/molecule/test/a_unit/test_shell.py
  src/molecule/test/a_unit/test_util.py
  src/molecule/test/b_functional/test_command.py
  src/molecule/util.py
Labels: skip-changelog

#3953 More type adoption
  src/molecule/test/a_unit/command/test_base.py
  src/molecule/test/a_unit/command/test_dependency.py
  src/molecule/test/a_unit/command/test_login.py
  src/molecule/test/a_unit/command/test_prepare.py
  src/molecule/test/a_unit/driver/test_delegated.py
  src/molecule/test/a_unit/provisioner/test_ansible_playbook.py
  src/molecule/test/a_unit/test_config.py
  src/molecule/test/a_unit/test_platforms.py
  src/molecule/test/a_unit/test_scenarios_ordered.py
  src/molecule/test/a_unit/test_state.py
Labels: skip-changelog

#3954 More types
  src/molecule/status.py
  src/molecule/test/a_unit/command/test_base.py
  src/molecule/test/a_unit/command/test_check.py
  src/molecule/test/a_unit/command/test_cleanup.py
  src/molecule/test/a_unit/command/test_create.py
  src/molecule/test/a_unit/command/test_dependency.py
  src/molecule/test/a_unit/command/test_destroy.py
  src/molecule/test/a_unit/command/test_idempotence.py
  src/molecule/test/a_unit/command/test_list.py
  src/molecule/test/a_unit/command/test_login.py
  src/molecule/test/a_unit/command/test_prepare.py
  src/molecule/test/a_unit/command/test_side_effect.py
  src/molecule/test/a_unit/command/test_syntax.py
  src/molecule/test/a_unit/command/test_verify.py
  src/molecule/test/a_unit/dependency/ansible_galaxy/test_collections.py
  src/molecule/test/a_unit/dependency/ansible_galaxy/test_roles.py
  src/molecule/test/a_unit/dependency/test_shell.py
  src/molecule/test/a_unit/driver/test_delegated.py
  src/molecule/test/a_unit/provisioner/test_ansible.py
  src/molecule/test/a_unit/provisioner/test_ansible_playbook.py
  src/molecule/test/a_unit/provisioner/test_ansible_playbooks.py
  src/molecule/test/a_unit/test_config.py
  src/molecule/test/a_unit/test_logger.py
  src/molecule/test/a_unit/test_platforms.py
  src/molecule/test/a_unit/test_scenario.py
  src/molecule/test/a_unit/test_scenarios.py
  src/molecule/test/a_unit/test_state.py
  src/molecule/test/a_unit/test_util.py
  src/molecule/test/a_unit/verifier/test_ansible.py
  src/molecule/test/a_unit/verifier/test_testinfra.py
Labels: skip-changelog

#3955 More types
  src/molecule/test/a_unit/command/test_base.py
  src/molecule/test/a_unit/command/test_idempotence.py
  src/molecule/test/a_unit/dependency/test_shell.py
  src/molecule/test/a_unit/test_config.py
  src/molecule/test/a_unit/test_util.py
  src/molecule/test/a_unit/verifier/test_ansible.py
  src/molecule/util.py
Labels: skip-changelog

#3956 Remove ability to configure collections-path and roles-path for dependency
  .github/workflows/tox.yml
  docs/next.md
  mkdocs.yml
  src/molecule/dependency/ansible_galaxy/base.py
  src/molecule/dependency/ansible_galaxy/collections.py
  src/molecule/dependency/ansible_galaxy/roles.py
  src/molecule/provisioner/ansible.py
  src/molecule/test/a_unit/dependency/ansible_galaxy/test_collections.py
  src/molecule/test/a_unit/dependency/ansible_galaxy/test_roles.py
  src/molecule/test/a_unit/provisioner/test_ansible.py
Labels: major

#3959 Reimplemented templating (init command)
  .ansible.cfg
  .config/requirements-lock.txt
  .config/requirements.in
  .config/requirements.txt
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  .yamllint
  docs/examples.md
  docs/getting-started.md
  docs/usage.md
  pyproject.toml
  src/molecule/command/cleanup.py
  src/molecule/command/init/base.py
  src/molecule/command/init/init.py
  src/molecule/command/init/role.py
  src/molecule/command/init/scenario.py
  src/molecule/command/verify.py
  src/molecule/config.py
  src/molecule/cookiecutter/molecule/cookiecutter.json
  src/molecule/cookiecutter/molecule/{{cookiecutter.role_name}}/.yamllint
  src/molecule/cookiecutter/molecule/{{cookiecutter.role_name}}/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/molecule.yml
  src/molecule/cookiecutter/scenario/driver/delegated/cookiecutter.json
  src/molecule/cookiecutter/scenario/driver/delegated/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/INSTALL.rst
  src/molecule/cookiecutter/scenario/driver/delegated/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/converge.yml
  src/molecule/cookiecutter/scenario/verifier/ansible/cookiecutter.json
  src/molecule/cookiecutter/scenario/verifier/ansible/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/verify.yml
  src/molecule/cookiecutter/scenario/verifier/testinfra/cookiecutter.json
  src/molecule/cookiecutter/scenario/verifier/testinfra/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/{{cookiecutter.verifier_directory}}/conftest.py
  src/molecule/cookiecutter/scenario/verifier/testinfra/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/{{cookiecutter.verifier_directory}}/test_default.py
  src/molecule/data/init-scenario.yml
  src/molecule/data/templates/scenario/converge.yml.j2
  src/molecule/data/templates/scenario/create.yml.j2
  src/molecule/data/templates/scenario/destroy.yml.j2
  src/molecule/data/templates/scenario/molecule.yml.j2
  src/molecule/driver/base.py
  src/molecule/test/a_unit/command/init/test_role.py
  src/molecule/test/a_unit/command/init/test_scenario.py
  src/molecule/test/a_unit/cookiecutter/test_molecule.py
  src/molecule/test/b_functional/conftest.py
  src/molecule/test/b_functional/test_command.py
  src/molecule/test/resources/templates/cookiecutter.json
  src/molecule/test/resources/templates/{{cookiecutter.repo_name}}/template.yml
  src/molecule/verifier/base.py
Labels: major

#3961 Temporary disable support for external drivers
  pyproject.toml
  src/molecule/api.py
Labels: major

#3960 Rename delegated driver to default
  pyproject.toml
  src/molecule/config.py
  src/molecule/data/driver.json
  src/molecule/data/molecule.json
  src/molecule/driver/base.py
  src/molecule/driver/delegated.py
  src/molecule/test/a_unit/command/conftest.py
  src/molecule/test/a_unit/command/init/test_scenario.py
  src/molecule/test/a_unit/command/test_create.py
  src/molecule/test/a_unit/command/test_list.py
  src/molecule/test/a_unit/conftest.py
  src/molecule/test/a_unit/cookiecutter/test_molecule.py
  src/molecule/test/a_unit/driver/test_delegated.py
  src/molecule/test/a_unit/model/v2/test_driver_section.py
  src/molecule/test/a_unit/provisioner/test_ansible_playbooks.py
  src/molecule/test/a_unit/test_api.py
  src/molecule/test/a_unit/test_config.py
  src/molecule/test/a_unit/test_interpolation.py
  src/molecule/test/b_functional/conftest.py
  src/molecule/test/b_functional/test_command.py
  src/molecule/test/resources/molecule.yml
  src/molecule/test/resources/sample-collection/molecule/default/molecule.yml
  src/molecule/test/resources/schema_instance_files/invalid/molecule_delegated.yml
  src/molecule/test/resources/schema_instance_files/valid/molecule.yml
  src/molecule/test/scenarios/cleanup/molecule/default/molecule.yml
  src/molecule/test/scenarios/dependency/molecule/ansible-galaxy/molecule.yml
  src/molecule/test/scenarios/dependency/molecule/shell/molecule.yml
  src/molecule/test/scenarios/driver/delegated/molecule/default/molecule.yml
  src/molecule/test/scenarios/driver/delegated_invalid_role_name_with_role_name_check_equals_to_1/molecule/default/molecule.yml
  src/molecule/test/scenarios/host_group_vars/molecule/default/molecule.yml
  src/molecule/test/scenarios/host_group_vars/molecule/links/molecule.yml
  src/molecule/test/scenarios/idempotence/molecule/raises/molecule.yml
  src/molecule/test/scenarios/overrride_driver/molecule/default/molecule.yml
  src/molecule/test/scenarios/side_effect/molecule/default/molecule.yml
  src/molecule/test/scenarios/test_destroy_strategy/molecule/default/molecule.yml
  src/molecule/test/scenarios/verifier/molecule/testinfra-pre-commit/molecule.yml
  src/molecule/test/scenarios/verifier/molecule/testinfra/molecule.yml
Labels: major

#3958 Remove internal command baking
  docs/next.md
  src/molecule/data/templates/scenario/create.yml.j2
  src/molecule/data/templates/scenario/destroy.yml.j2
  src/molecule/dependency/ansible_galaxy/base.py
  src/molecule/dependency/base.py
  src/molecule/dependency/shell.py
  src/molecule/provisioner/ansible_playbook.py
  src/molecule/test/a_unit/dependency/ansible_galaxy/test_collections.py
  src/molecule/test/a_unit/dependency/ansible_galaxy/test_roles.py
  src/molecule/test/a_unit/dependency/test_shell.py
  src/molecule/test/a_unit/provisioner/test_ansible_playbook.py
  src/molecule/test/a_unit/test_util.py
  src/molecule/test/a_unit/verifier/test_testinfra.py
  src/molecule/test/b_functional/test_command.py
  src/molecule/util.py
  src/molecule/verifier/testinfra.py
Labels: skip-changelog

#3964 Remove testinfra verifier
  .config/requirements-test.txt
  .config/requirements.txt
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  docs/ci.md
  docs/configuration.md
  docs/examples.md
  docs/getting-started.md
  docs/next.md
  pyproject.toml
  src/molecule/driver/base.py
  src/molecule/driver/delegated.py
  src/molecule/interpolation.py
  src/molecule/test/a_unit/cookiecutter/__init__.py
  src/molecule/test/a_unit/cookiecutter/test_molecule.py
  src/molecule/test/a_unit/driver/test_delegated.py
  src/molecule/test/a_unit/model/v2/test_verifier_section.py
  src/molecule/test/a_unit/test_api.py
  src/molecule/test/a_unit/verifier/test_testinfra.py
  src/molecule/test/resources/schema_instance_files/valid/molecule.yml
  src/molecule/test/scenarios/.flake8
  src/molecule/test/scenarios/cleanup/molecule/default/tests/test_cleanup.py
  src/molecule/test/scenarios/host_group_vars/molecule/links/converge.yml
  src/molecule/test/scenarios/host_group_vars/molecule/links/molecule.yml
  src/molecule/test/scenarios/side_effect/molecule/default/tests/test_side_effect.py
  src/molecule/test/scenarios/test_destroy_strategy/molecule/default/tests/test_destroy_strategy.py
  src/molecule/test/scenarios/verifier/.pre-commit-config.yaml
  src/molecule/test/scenarios/verifier/molecule/testinfra-pre-commit/converge.yml
  src/molecule/test/scenarios/verifier/molecule/testinfra-pre-commit/molecule.yml
  src/molecule/test/scenarios/verifier/molecule/testinfra-pre-commit/tests/test_testinfra_pre_commit.py
  src/molecule/test/scenarios/verifier/molecule/testinfra/converge.yml
  src/molecule/test/scenarios/verifier/molecule/testinfra/molecule.yml
  src/molecule/test/scenarios/verifier/molecule/testinfra/shared/test_shared.py
  src/molecule/test/scenarios/verifier/molecule/testinfra/tests/test_testinfra.py
  src/molecule/verifier/testinfra.py
Labels: major

#3974 Revert "Temporary disable support for external drivers"
  pyproject.toml
  src/molecule/api.py
Labels: major

#3975 Update documentation
  docs/configuration.md
  docs/faq.md
  docs/next.md
Labels: bug

#3978 Add example of using docker collection using default driver
  .github/workflows/tox.yml
  docs/docker.md
  mkdocs.yml
  molecule/docker/converge.yml
  molecule/docker/create.yml
  molecule/docker/destroy.yml
  molecule/docker/molecule.yml
  molecule/docker/requirements.yml
  molecule/docker/tasks/create-fail.yml
  src/molecule/test/b_functional/test_command.py
Labels: bug

#3981 Remove constraints requirement files
  .config/requirements-lock.txt
  .config/requirements.txt
  .github/dependabot.yml
  .pre-commit-config.yaml
  docs/contributing.md
  pyproject.toml
  tox.ini
Labels: bug

#3979 Avoid reinstalling dependencies
  src/molecule/dependency/ansible_galaxy/base.py
  src/molecule/test/a_unit/dependency/ansible_galaxy/test_collections.py
  src/molecule/test/a_unit/dependency/ansible_galaxy/test_roles.py
Labels: bug
