Repository ansible/molecule, pull requests merged in 2023-06, with the labels that each got.

#3904 Use backwards incompatible change from ansible-compat 4.0.1
  .config/requirements-lock.txt
  .config/requirements.in
  .config/requirements.txt
  .pre-commit-config.yaml
  src/molecule/command/init/role.py
  src/molecule/cookiecutter/scenario/driver/delegated/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/create.yml
  src/molecule/cookiecutter/scenario/driver/delegated/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/destroy.yml
  src/molecule/test/functional/.ansible-lint
  src/molecule/test/functional/conftest.py
  src/molecule/util.py
Labels: bug

#3899 Improve documentation for upgrade scenario
  docs/installation.md
Labels: enhancement, docs

#3916 Update dependency doc
  src/molecule/dependency/ansible_galaxy/__init__.py
Labels: enhancement, docs

#3928 `tox -e deps` needs to be allowed to run git
  tox.ini
Labels: bug, test, skip-changelog

#3923 Fix dead link in documentation
  docs/contributing.md
Labels: bug, docs

#3932 Adds Support for Shell Type Instance Param to Delegated Driver
  src/molecule/driver/delegated.py
Labels: bug

#3929 Document procedure for updating dependencies
  docs/contributing.md
Labels: docs, skip-changelog

#3911 Fix quoted strings templating
  .github/workflows/tox.yml
  src/molecule/test/unit/test_util.py
  src/molecule/util.py
Labels: bug

#3938 Update linters
  .pre-commit-config.yaml
  src/molecule/interpolation.py
  src/molecule/model/schema_v3.py
  src/molecule/provisioner/ansible.py
  src/molecule/provisioner/ansible_playbooks.py
  src/molecule/scenario.py
  src/molecule/shell.py
  src/molecule/test/functional/test_command.py
  src/molecule/test/unit/model/v2/test_driver_section.py
  src/molecule/test/unit/model/v2/test_platforms_section.py
Labels: skip-changelog

#3940 Fix documentation links
  .config/requirements-docs.txt
  .config/requirements.txt
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  docs/ci.md
  docs/contributing.md
  docs/faq.md
  docs/getting-started.md
  docs/usage.md
  linkcheckerrc
  mkdocs.yml
  tox.ini
Labels: bug

#3946 Make driver optional in molecule.yml file
  src/molecule/data/molecule.json
Labels: bug

#3948 Improve how executed commands are logged
  src/molecule/provisioner/ansible_playbook.py
  src/molecule/test/unit/command/init/test_role.py
  src/molecule/test/unit/command/init/test_scenario.py
  src/molecule/test/unit/command/test_base.py
  src/molecule/test/unit/command/test_check.py
  src/molecule/test/unit/command/test_cleanup.py
  src/molecule/test/unit/command/test_converge.py
  src/molecule/test/unit/command/test_create.py
  src/molecule/test/unit/command/test_dependency.py
  src/molecule/test/unit/command/test_destroy.py
  src/molecule/test/unit/command/test_idempotence.py
  src/molecule/test/unit/command/test_login.py
  src/molecule/test/unit/command/test_prepare.py
  src/molecule/test/unit/command/test_side_effect.py
  src/molecule/test/unit/command/test_syntax.py
  src/molecule/test/unit/command/test_verify.py
  src/molecule/test/unit/conftest.py
  src/molecule/test/unit/dependency/ansible_galaxy/test_collections.py
  src/molecule/test/unit/dependency/ansible_galaxy/test_roles.py
  src/molecule/test/unit/dependency/test_shell.py
  src/molecule/test/unit/provisioner/test_ansible.py
  src/molecule/test/unit/provisioner/test_ansible_playbook.py
  src/molecule/test/unit/test_config.py
  src/molecule/test/unit/test_scenarios.py
  src/molecule/test/unit/test_util.py
  src/molecule/test/unit/verifier/test_ansible.py
  src/molecule/test/unit/verifier/test_testinfra.py
  src/molecule/util.py
Labels: bug

#3949 Avoid skipping create and destroy steps on delegated
  .github/workflows/tox.yml
  src/molecule/command/create.py
  src/molecule/command/destroy.py
  src/molecule/test/unit/command/test_create.py
  src/molecule/test/unit/command/test_destroy.py
Labels: feature
