Repository ansible/molecule, pull requests merged in 2023-08, with the labels that each got.

#3972 Add example of integration with kubevirt
  docs/kubevirt.md
  mkdocs.yml
  molecule/kubevirt/converge.yml
  molecule/kubevirt/create.yml
  molecule/kubevirt/destroy.yml
  molecule/kubevirt/molecule.yml
  molecule/kubevirt/requirements.yml
  molecule/kubevirt/tasks/create_vm.yml
  molecule/kubevirt/tasks/create_vm_dictionary.yml
Labels: bug, docs

#3989 Allow molecule to list scenarios present under molecule directory within a collection
  .config/requirements.in
  .pre-commit-config.yaml
  src/molecule/command/base.py
  src/molecule/command/list.py
Labels: enhancement

#3985 Update documentation
  docs/examples.md
  docs/getting-started.md
  docs/images/collection_structure_and_ansible_cfg.png
  docs/next.md
  docs/usage.md
Labels: bug

#3997 Scaffold future docs structure
  .gitignore
  docs/working/contributor_guide/code_of_conduct.md
  docs/working/contributor_guide/contribution_requirements.md
  docs/working/contributor_guide/developer_contact.md
  docs/working/contributor_guide/environment_setup.md
  docs/working/examples/example_1.md
  docs/working/examples/example_2.md
  docs/working/examples/example_3.md
  docs/working/faq/faq.md
  docs/working/getting_started/getting_started.md
  docs/working/installation/install.md
  docs/working/installation/upgrade.md
  docs/working/introduction/introduction.md
  docs/working/references/cli.md
  docs/working/references/configuration.md
  docs/working/references/porting_change_log.md
  docs/working/references/road_map.md
  docs/working/user_guide/ci_integration.md
  docs/working/user_guide/creating_testing_collection.md
  docs/working/user_guide/testing_existing_collection.md
  docs/working/user_guide/testing_existing_roles.md
  docs/working/user_guide/understanding.md
  docs/working/user_guide/using_tox-ansible.md
  mkdocs.yml
Labels: bug

#3996 Ignore scenarios in virtual envrionments
  .github/workflows/tox.yml
  .gitignore
  src/molecule/command/base.py
  src/molecule/test/b_functional/test_command.py
Labels: bug

#4007 Update pre-commit
  .pre-commit-config.yaml
Labels: skip-changelog

#4010 fix: remove `role` from `init` help info
  src/molecule/command/init/init.py
Labels: bug

#4014 Pass environment in testinfra
  .github/workflows/tox.yml
  src/molecule/test/a_unit/verifier/test_testinfra.py
  src/molecule/verifier/testinfra.py
Labels: bug

#4022 Update ansible-compat to v4.1.7
  .config/requirements.in
  .pre-commit-config.yaml
Labels: bug

#4028 Update `ansible-compat` to v4.1.8
  .config/requirements.in
  .pre-commit-config.yaml
Labels: skip-changelog
