Repository ansible/molecule, pull requests merged in 2023-02, with the labels that each got.

#3822 Fix test dependencies
  pyproject.toml
  requirements.txt
Labels: skip-changelog

#3824 Remove embedded dockerfile
  .github/workflows/tox.yml
  src/molecule/data/Dockerfile.j2
  src/molecule/data/validate-dockerfile.yml
  tox.ini
Labels: bug

#3811 Replace sphinx documentation with mkdocs
  .flake8
  .gitignore
  .readthedocs.yml
  docs/_static/images/logo.png
  docs/ci.md
  docs/ci.rst
  docs/conf.py
  docs/configuration.md
  docs/configuration.rst
  docs/contributing.md
  docs/contributing.rst
  docs/examples.md
  docs/examples.rst
  docs/faq.md
  docs/faq.rst
  docs/getting-started.md
  docs/getting-started.rst
  docs/images/favicon.ico
  docs/images/logo.png
  docs/images/logo.svg
  docs/index.md
  docs/index.rst
  docs/installation.md
  docs/installation.rst
  docs/usage.md
  docs/usage.rst
  mkdocs.yml
  pyproject.toml
  requirements.txt
  src/molecule/command/check.py
  src/molecule/command/cleanup.py
  src/molecule/command/converge.py
  src/molecule/command/create.py
  src/molecule/command/dependency.py
  src/molecule/command/destroy.py
  src/molecule/command/idempotence.py
  src/molecule/command/list.py
  src/molecule/command/login.py
  src/molecule/command/side_effect.py
  src/molecule/command/syntax.py
  src/molecule/command/test.py
  src/molecule/command/verify.py
  src/molecule/config.py
  src/molecule/dependency/ansible_galaxy/__init__.py
  src/molecule/dependency/shell.py
  src/molecule/driver/base.py
  src/molecule/driver/delegated.py
  src/molecule/interpolation.py
  src/molecule/platforms.py
  src/molecule/provisioner/ansible.py
  src/molecule/scenario.py
  src/molecule/state.py
  src/molecule/verifier/ansible.py
  src/molecule/verifier/testinfra.py
  tox.ini
Labels: bug, enhancement

#3816 set better indentation
  src/molecule/cookiecutter/scenario/verifier/ansible/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/verify.yml
Labels: bug

#3812 Documentation: Improve group names
  src/molecule/provisioner/ansible.py
Labels: bug
