Repository ansible/molecule, pull requests merged in 2023-01, with the labels that each got.

#3797 Bump test dependencies
  .github/workflows/release.yml
  .github/workflows/tox.yml
  .npmrc
  .pre-commit-config.yaml
  .pyup.yml
  docs/contributing.rst
  pyproject.toml
  requirements.txt
  tools/test-schema/negative_test/molecule/platforms_children/molecule.yml.md
  tools/test-schema/negative_test/molecule/platforms_networks/molecule.yml.md
  tools/test-schema/package-lock.json
  tools/test-schema/package.json
  tools/test-schema/src/schema.spec.ts
  tox.ini
Labels: bug

#3796 Fixed typo in `docs/ci.rst`
  docs/ci.rst
Labels: bug

#3778 Reorder heading and reformat badges
  README.md
Labels: bug

#3798 Fix rpm building
  .packit.yaml
Labels: bug

#3799 Require ansible-core>=2.12.10
  pyproject.toml
Labels: enhancement

#3800 Update test dependencies
  .coveragerc
  .github/workflows/tox.yml
  pyproject.toml
  requirements.txt
  tox.ini
Labels: bug

#3802 Remove lint command
  .github/workflows/tox.yml
  docs/configuration.rst
  docs/getting-started.rst
  docs/usage.rst
  src/molecule/command/__init__.py
  src/molecule/command/init/role.py
  src/molecule/command/init/scenario.py
  src/molecule/command/lint.py
  src/molecule/command/test.py
  src/molecule/config.py
  src/molecule/data/molecule.json
  src/molecule/lint/__init__.py
  src/molecule/lint/base.py
  src/molecule/scenario.py
  src/molecule/scenarios.py
  src/molecule/shell.py
  src/molecule/test/functional/test_command.py
  src/molecule/test/unit/command/test_lint.py
  src/molecule/test/unit/test_config.py
  src/molecule/test/unit/test_scenario.py
  src/molecule/test/unit/test_scenarios.py
  tools/test-schema/test/molecule/cluster/molecule.yml
  tools/test-schema/test/molecule/default/molecule.yml
  tools/test-schema/test/molecule/vagrant/molecule.yml
Labels: bug, enhancement, deprecated

#3804 Use dynamic matrix
  .github/workflows/tox.yml
Labels: skip-changelog

#3805 Document molecule-plugins package
  docs/examples.rst
  docs/installation.rst
  tox.ini
Labels: bug

#3795 Add support for custom driver name
  .github/workflows/tox.yml
  src/molecule/data/molecule.json
  src/molecule/model/schema_v3.py
  src/molecule/test/unit/model/v2/test_driver_section.py
Labels: bug
