Repository ansible/molecule, pull requests merged in 2023-04, with the labels that each got.

#3866 Add tags document
  src/molecule/provisioner/ansible.py
Labels: enhancement, docs

#3863 fix link to monorepo under faq
  docs/faq.md
Labels: bug, docs

#3872 Update linters
  .pre-commit-config.yaml
  .pylintrc
  pyproject.toml
Labels: skip-changelog

#3873 Update test dependencies
  requirements.txt
Labels: skip-changelog

#3876 GHA maintenance
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#3878 Add documentation redirects
  .github/workflows/redirects.yml
  docs/configuration.md
  docs/google04e29a42ae6e6cbc.html
  docs/redirects.yml
  pyproject.toml
Labels: skip-changelog

#3880 Add `consider-using-in` check
  pyproject.toml
  src/molecule/command/list.py
Labels: bug

#3879 Refactor dependency locks
  .config/requirements-docs.txt
  .config/requirements-lock.txt
  .config/requirements-test.txt
  .config/requirements.in
  .config/requirements.txt
  .gitignore
  .pre-commit-config.yaml
  pyproject.toml
  src/molecule/__init__.py
  src/molecule/driver/base.py
  src/molecule/scenarios.py
  src/molecule/test/functional/conftest.py
  tox.ini
Labels: bug

#3882 Add `implicit-str-concat` & `inconsistent-return-statements` check
  pyproject.toml
  src/molecule/config.py
  src/molecule/provisioner/ansible.py
  src/molecule/provisioner/ansible_playbooks.py
  src/molecule/test/unit/command/init/test_scenario.py
  src/molecule/test/unit/dependency/ansible_galaxy/test_roles.py
Labels: bug

#3884 Add `no-else-return`, `no-else-raise` & `logging-not-lazy` check
  pyproject.toml
  src/molecule/api.py
  src/molecule/config.py
  src/molecule/logger.py
  src/molecule/provisioner/ansible_playbooks.py
  src/molecule/scenario.py
  src/molecule/util.py
  src/molecule/verifier/testinfra.py
Labels: bug

#3885 Add `raise-missing-from` rule
  pyproject.toml
  src/molecule/interpolation.py
Labels: bug

#3886 Fix colors when displaying plugin versions
  src/molecule/shell.py
Labels: bug

#3887 More ruff fixes
  .pre-commit-config.yaml
  pyproject.toml
  src/molecule/command/login.py
  src/molecule/provisioner/ansible_playbooks.py
  src/molecule/test/functional/conftest.py
  src/molecule/util.py
Labels: bug

#3889 Address ruff S, EXE skips
  pyproject.toml
  src/molecule/command/init/scenario.py
  src/molecule/command/test.py
  src/molecule/provisioner/ansible.py
  src/molecule/shell.py
  src/molecule/test/scenarios/verifier/molecule/testinfra-pre-commit/tests/test_testinfra_pre_commit.py
  src/molecule/test/unit/command/test_base.py
  src/molecule/test/unit/dependency/ansible_galaxy/test_roles.py
Labels: bug

#3892 Add `unnecessary-lambda` check
  pyproject.toml
  src/molecule/test/unit/conftest.py
Labels: bug

#3893 Add `unidiomatic-typecheck` check
  pyproject.toml
  src/molecule/test/unit/model/v2/test_driver_section.py
Labels: bug

#3896 Add `subprocess-run-check`
  pyproject.toml
  src/molecule/command/login.py
  src/molecule/test/functional/conftest.py
Labels: bug

#3898 Use api to get driver schema file
  src/molecule/driver/base.py
  src/molecule/driver/delegated.py
  src/molecule/model/schema_v3.py
Labels: bug
