Repository ansible/molecule, pull requests merged in 2024-03, with the labels that each got.

#4147 Update ack.yml
  .github/workflows/ack.yml
Labels: skip-changelog

#4145 Set ANSIBLE_FORCE_COLOR sooner to fix missing color output in tmux
  src/molecule/console.py
Labels: bug

#4154 Suggest adt installation
  .config/requirements-docs.txt
  docs/ci.md
  docs/guides/docker-rootless.md
  docs/installation.md
  mkdocs.yml
  pyproject.toml
  tox.ini
Labels: docs, skip-changelog
