Repository ansible/molecule, pull requests merged in 2024-12, with the labels that each got.

#4334 Add docstrings and type hints to verifier subdirectory.
  .config/pydoclint-baseline.txt
  src/molecule/config.py
  src/molecule/provisioner/ansible.py
  src/molecule/types.py
  src/molecule/util.py
  src/molecule/verifier/__init__.py
  src/molecule/verifier/ansible.py
  src/molecule/verifier/base.py
  src/molecule/verifier/testinfra.py
Labels: skip-changelog

#4331 Add docstrings and type hints to dependency plugins
  .config/pydoclint-baseline.txt
  src/molecule/command/dependency.py
  src/molecule/dependency/__init__.py
  src/molecule/dependency/ansible_galaxy/__init__.py
  src/molecule/dependency/ansible_galaxy/base.py
  src/molecule/dependency/ansible_galaxy/collections.py
  src/molecule/dependency/ansible_galaxy/roles.py
  src/molecule/dependency/base.py
  src/molecule/dependency/shell.py
  src/molecule/provisioner/ansible.py
  src/molecule/types.py
  src/molecule/util.py
  tests/unit/test_util.py
Labels: skip-changelog

#4337 Miscellaneous additional cleanup
  src/molecule/command/__init__.py
  src/molecule/config.py
  src/molecule/driver/base.py
  src/molecule/driver/delegated.py
  src/molecule/model/schema_v3.py
  src/molecule/provisioner/ansible.py
  src/molecule/state.py
  src/molecule/verifier/testinfra.py
Labels: skip-changelog

#4341 Return absolute path without resolving symlinks
  src/molecule/util.py
  tests/unit/test_util.py
Labels: bug

#4340 Make molecule collection-aware
  src/molecule/config.py
  src/molecule/types.py
  src/molecule/util.py
  tests/fixtures/resources/broken-collection/galaxy.yml
  tests/unit/test_config.py
  tests/unit/test_util.py
Labels: enhancement
