Repository ansible/molecule, pull requests merged in 2024-02, with the labels that each got.

#4132 GHA maintenance
  .github/CODEOWNERS
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  .github/workflows/tox.yml
  codecov.yml
Labels: skip-changelog

#4126 Adding molecule template based on `driver.name`
  src/molecule/data/init-scenario.yml
  src/molecule/data/templates/scenario/molecule.yml.j2
Labels: minor

#4130 Update dependencies to include new mkdocs-ansible branding
  .config/requirements-docs.txt
  mkdocs.yml
  tox.ini
Labels: skip-changelog, dependencies

#4133 Fix background color on matrix command
  src/molecule/util.py
Labels: bug

#4134 Fix symlinks creation in ansible provisioneer
  src/molecule/provisioner/ansible.py
Labels: bug
