Repository ansible/molecule, pull requests merged in 2024-09, with the labels that each got.

#4281 Community comms
  README.md
  docs/contributing.md
  mkdocs.yml
Labels: skip-changelog

#4279 Fix: Incorrect pip install documentation
  docs/installation.md
Labels: bug

#4158 dynamically get the nodeport host
  docs/examples/kubevirt.md
  tests/fixtures/integration/test_command/molecule/kubevirt/destroy.yml
  tests/fixtures/integration/test_command/molecule/kubevirt/molecule.yml
  tests/fixtures/integration/test_command/molecule/kubevirt/tasks/create_vm.yml
  tests/fixtures/integration/test_command/molecule/kubevirt/tasks/create_vm_dictionary.yml
Labels: enhancement

#4240 Refactor API to use standard types
  .config/pydoclint-baseline.txt
  pyproject.toml
  src/molecule/api.py
  src/molecule/command/drivers.py
  src/molecule/command/reset.py
  src/molecule/config.py
  src/molecule/driver/base.py
  src/molecule/driver/delegated.py
  src/molecule/provisioner/ansible.py
  src/molecule/shell.py
  src/molecule/verifier/ansible.py
  src/molecule/verifier/base.py
  src/molecule/verifier/testinfra.py
  tests/unit/driver/test_delegated.py
  tests/unit/test_api.py
  tests/unit/test_config.py
Labels: bug
