Repository ansible/molecule, pull requests merged in 2025-01, with the labels that each got.

#4352 Update test dependencies
  .config/constraints.txt
  .config/requirements-test.txt
  .pre-commit-config.yaml
Labels: skip-changelog

#4356 Fix side_effect arguments
  src/molecule/provisioner/ansible.py
Labels: bug

#4358 Skip running test_docker on macos due to upstream bug
  tests/integration/test_command.py
Labels: skip-changelog

#4359 Make run_command part of App class
  .config/pydoclint-baseline.txt
  pyproject.toml
  src/molecule/app.py
  src/molecule/command/init/scenario.py
  src/molecule/config.py
  src/molecule/dependency/base.py
  src/molecule/provisioner/ansible_playbook.py
  src/molecule/util.py
  src/molecule/verifier/testinfra.py
  tests/conftest.py
  tests/fixtures/integration/test_command/scenarios/cleanup/molecule/default/tests/test_cleanup.py
  tests/fixtures/integration/test_command/scenarios/side_effect/molecule/default/tests/test_side_effect.py
  tests/fixtures/integration/test_command/scenarios/test_destroy_strategy/molecule/default/tests/test_destroy_strategy.py
  tests/fixtures/integration/test_command/scenarios/verifier/molecule/testinfra-pre-commit/tests/test_testinfra_pre_commit.py
  tests/fixtures/integration/test_command/scenarios/verifier/molecule/testinfra/shared/test_shared.py
  tests/fixtures/integration/test_command/scenarios/verifier/molecule/testinfra/tests/test_testinfra.py
  tests/integration/conftest.py
  tests/integration/test_command.py
  tests/unit/command/conftest.py
  tests/unit/command/init/test_scenario.py
  tests/unit/command/test_base.py
  tests/unit/command/test_check.py
  tests/unit/command/test_cleanup.py
  tests/unit/command/test_converge.py
  tests/unit/command/test_create.py
  tests/unit/command/test_dependency.py
  tests/unit/command/test_destroy.py
  tests/unit/command/test_idempotence.py
  tests/unit/command/test_list.py
  tests/unit/command/test_prepare.py
  tests/unit/command/test_side_effect.py
  tests/unit/command/test_syntax.py
  tests/unit/command/test_verify.py
  tests/unit/conftest.py
  tests/unit/dependency/ansible_galaxy/test_collections.py
  tests/unit/dependency/ansible_galaxy/test_roles.py
  tests/unit/dependency/test_shell.py
  tests/unit/driver/test_delegated.py
  tests/unit/model/v2/test_dependency_section.py
  tests/unit/model/v2/test_driver_section.py
  tests/unit/model/v2/test_platforms_section.py
  tests/unit/model/v2/test_provisioner_section.py
  tests/unit/model/v2/test_scenario_section.py
  tests/unit/model/v2/test_schema.py
  tests/unit/model/v2/test_verifier_section.py
  tests/unit/provisioner/test_ansible.py
  tests/unit/provisioner/test_ansible_playbook.py
  tests/unit/provisioner/test_ansible_playbooks.py
  tests/unit/test_config.py
  tests/unit/test_interpolation.py
  tests/unit/test_logger.py
  tests/unit/test_platforms.py
  tests/unit/test_scenario.py
  tests/unit/test_scenarios.py
  tests/unit/test_scenarios_ordered.py
  tests/unit/test_state.py
  tests/unit/test_util.py
  tests/unit/verifier/test_ansible.py
  tests/unit/verifier/test_testinfra.py
Labels: bug

#4361 Use fixed GHA runners
  .github/workflows/redirects.yml
  .github/workflows/release.yml
  .readthedocs.yml
  docs/ci.md
Labels: skip-changelog

#4367 Fix constraints use with uv
  .config/constraints.txt
  .pre-commit-config.yaml
  pyproject.toml
  tox.ini
Labels: bug

#4369 Update linters
  .config/pydoclint-baseline.txt
  .pre-commit-config.yaml
  src/molecule/command/base.py
  src/molecule/dependency/ansible_galaxy/collections.py
  src/molecule/types.py
Labels: bug

#4364 Refactor tests
  .config/pydoclint-baseline.txt
  tests/conftest.py
  tests/integration/test_command.py
  tests/unit/model/v2/test_schema.py
Labels: skip-changelog

#4363 Minor test improvements
  .gitignore
  .readthedocs.yml
  molecule
  pyproject.toml
  src/molecule/scenario.py
  tests/unit/test_scenario.py
  tox.ini
Labels: skip-changelog

#4375 Validate docker installation before running docker tests
  tests/integration/test_command.py
Labels: bug

#4376 Drop code related to unsupported ansible versions
  README.md
  docs/index.md
  docs/installation.md
  src/molecule/config.py
  src/molecule/provisioner/ansible.py
  tests/fixtures/integration/test_command/scenarios/driver/delegated/meta/main.yml
  tests/fixtures/integration/test_command/scenarios/driver/delegated_invalid_role_name_with_role_name_check_equals_to_1/meta/main.yml
  tests/fixtures/resources/roles/molecule/meta/main.yml
  tox.ini
Labels: bug

#4380 Remove code that modifies ansible import paths
  .gitignore
  docs/faq.md
  docs/guides/monolith.md
  pyproject.toml
  src/molecule/provisioner/ansible.py
  tests/fixtures/integration/test_command/scenarios/dependency/molecule/shell/molecule.yml
  tests/unit/provisioner/test_ansible.py
  tests/unit/verifier/test_testinfra.py
  tox.ini
Labels: major

#4381 Update ansible-compat to `v25.1.0`
  .config/constraints.txt
  .config/requirements.in
  .pre-commit-config.yaml
Labels: bug

#4362 Change location of ephemeral directory
  src/molecule/scenario.py
  src/molecule/text.py
  tests/unit/test_scenario.py
  tox.ini
Labels: enhancement
