Repository ansible/molecule, pull requests merged in 2025-03, with the labels that each got.

#4403 Update recommended container
  docs/installation.md
Labels: bug

#4411 Pull out common action options
  src/molecule/command/base.py
  src/molecule/command/check.py
  src/molecule/command/cleanup.py
  src/molecule/command/converge.py
  src/molecule/command/create.py
  src/molecule/command/dependency.py
  src/molecule/command/destroy.py
  src/molecule/command/idempotence.py
  src/molecule/command/prepare.py
  src/molecule/command/side_effect.py
  src/molecule/command/syntax.py
  src/molecule/command/test.py
  src/molecule/command/verify.py
Labels: minor

#4405 End-of-run summary report
  .config/dictionary.txt
  src/molecule/command/base.py
  src/molecule/command/check.py
  src/molecule/command/cleanup.py
  src/molecule/command/converge.py
  src/molecule/command/create.py
  src/molecule/command/dependency.py
  src/molecule/command/destroy.py
  src/molecule/command/idempotence.py
  src/molecule/command/prepare.py
  src/molecule/command/side_effect.py
  src/molecule/command/syntax.py
  src/molecule/command/test.py
  src/molecule/command/verify.py
  src/molecule/provisioner/ansible_playbook.py
  src/molecule/scenario.py
  src/molecule/scenarios.py
  src/molecule/types.py
  tests/integration/test_command.py
Labels: enhancement

#4413 Replace internal calls to SystemExit with custom exception
  src/molecule/command/base.py
  src/molecule/command/idempotence.py
  src/molecule/exceptions.py
  src/molecule/util.py
  tests/unit/command/test_base.py
  tests/unit/command/test_idempotence.py
Labels: bug
