Repository ansible/molecule, pull requests merged in 2025-02, with the labels that each got.

#4388 Select and exclude multiple scenarios
  src/molecule/command/base.py
  src/molecule/command/check.py
  src/molecule/command/cleanup.py
  src/molecule/command/converge.py
  src/molecule/command/create.py
  src/molecule/command/dependency.py
  src/molecule/command/destroy.py
  src/molecule/command/idempotence.py
  src/molecule/command/list.py
  src/molecule/command/login.py
  src/molecule/command/matrix.py
  src/molecule/command/prepare.py
  src/molecule/command/reset.py
  src/molecule/command/side_effect.py
  src/molecule/command/syntax.py
  src/molecule/command/test.py
  src/molecule/command/verify.py
  src/molecule/scenarios.py
  tests/unit/command/test_base.py
  tests/unit/test_scenarios.py
Labels: enhancement

#4398 Avoid errors when running with readonly virtualenvs
  .config/constraints.txt
  .config/requirements.in
  .pre-commit-config.yaml
Labels: bug, dependencies

#4400 Fix molecule matrix with no scenario name.
  src/molecule/command/matrix.py
Labels: bug

#4384 Replace pipdeptree with uv pip tree
  .config/constraints.txt
  .config/requirements-docs.txt
  .config/requirements-test.txt
  .pre-commit-config.yaml
  pyproject.toml
  tools/smoketest.sh
  tox.ini
Labels: skip-changelog
