Repository ansible/molecule, pull requests merged in 2025-07, with the labels that each got.

#4452 Add shared-state argument
  src/molecule/command/base.py
  src/molecule/command/check.py
  src/molecule/command/cleanup.py
  src/molecule/command/converge.py
  src/molecule/command/create.py
  src/molecule/command/dependency.py
  src/molecule/command/destroy.py
  src/molecule/command/idempotence.py
  src/molecule/command/prepare.py
  src/molecule/command/side_effect.py
  src/molecule/command/syntax.py
  src/molecule/command/test.py
  src/molecule/command/verify.py
  src/molecule/config.py
  src/molecule/types.py
  tests/integration/test_command.py
  tests/unit/command/test_base.py
Labels: enhancement, feature

#4473 GHA release fixes
  .github/workflows/release.yml
  .gitignore
Labels: skip-changelog

#4472 Make sure path exist before writing
  src/molecule/command/base.py
  src/molecule/util.py
Labels: bug

#4478 Add scenario names to log messages for improved debugging
  src/molecule/ansi_output.py
  src/molecule/api.py
  src/molecule/command/base.py
  src/molecule/command/cleanup.py
  src/molecule/command/create.py
  src/molecule/command/destroy.py
  src/molecule/command/idempotence.py
  src/molecule/command/init/scenario.py
  src/molecule/command/login.py
  src/molecule/command/prepare.py
  src/molecule/command/side_effect.py
  src/molecule/console.py
  src/molecule/dependency/ansible_galaxy/base.py
  src/molecule/dependency/base.py
  src/molecule/dependency/shell.py
  src/molecule/logger.py
  src/molecule/provisioner/ansible.py
  src/molecule/provisioner/ansible_playbook.py
  src/molecule/provisioner/ansible_playbooks.py
  src/molecule/scenario.py
  src/molecule/verifier/ansible.py
  src/molecule/verifier/testinfra.py
  tests/unit/command/init/test_scenario.py
  tests/unit/test_ansi_output.py
  tests/unit/test_logger.py
Labels: enhancement

#4480 refactor(cli): Framework-agnostic CLI options with enhanced UX and comprehensive audit
  src/molecule/click_cfg.py
  src/molecule/command/base.py
  src/molecule/command/check.py
  src/molecule/command/cleanup.py
  src/molecule/command/converge.py
  src/molecule/command/create.py
  src/molecule/command/dependency.py
  src/molecule/command/destroy.py
  src/molecule/command/drivers.py
  src/molecule/command/idempotence.py
  src/molecule/command/init/init.py
  src/molecule/command/init/scenario.py
  src/molecule/command/list.py
  src/molecule/command/login.py
  src/molecule/command/matrix.py
  src/molecule/command/prepare.py
  src/molecule/command/reset.py
  src/molecule/command/side_effect.py
  src/molecule/command/syntax.py
  src/molecule/command/test.py
  src/molecule/command/verify.py
  src/molecule/constants.py
  src/molecule/shell.py
  tests/unit/test_click_cfg.py
Labels: chore

#4488 refactor: enhance Config and command base with comprehensive scenario-aware logging
  src/molecule/command/base.py
  src/molecule/config.py
  tests/unit/test_config.py
Labels: skip-changelog

#4491 Add StrEnum compatibility layer for Python 3.10
  .config/pydoclint-baseline.txt
  src/molecule/compatibility.py
  tests/unit/test_compatibility.py
Labels: chore
