Repository ansible/molecule, pull requests merged in 2025-05, with the labels that each got.

#4434 Update documentation to reflect creator-ee deprecation
  docs/ci.md
  docs/guides/inside-a-container.md
Labels: bug

#4432 Enable junit.xml reporting to codecov.io
  .gitignore
  pyproject.toml
  tools/report-coverage
  tox.ini
Labels: bug, test

#4416 Remove internal use of SystemExit part 2
  src/molecule/api.py
  src/molecule/command/base.py
  src/molecule/command/init/base.py
  src/molecule/command/init/scenario.py
  src/molecule/command/login.py
  src/molecule/config.py
  src/molecule/exceptions.py
  src/molecule/provisioner/ansible.py
  src/molecule/provisioner/ansible_playbook.py
  src/molecule/scenario.py
  src/molecule/scenarios.py
  src/molecule/util.py
  tests/unit/command/init/test_scenario.py
  tests/unit/command/test_base.py
  tests/unit/command/test_login.py
  tests/unit/provisioner/test_ansible.py
  tests/unit/provisioner/test_ansible_playbook.py
  tests/unit/test_config.py
  tests/unit/test_scenarios.py
  tests/unit/test_util.py
Labels: bug

#4441 chore: swap deprecated setting
  mise.toml
Labels: skip-changelog, chore

#4443 Add support for shared inventory between scenarios
  src/molecule/command/base.py
  src/molecule/command/check.py
  src/molecule/command/cleanup.py
  src/molecule/command/converge.py
  src/molecule/command/create.py
  src/molecule/command/dependency.py
  src/molecule/command/destroy.py
  src/molecule/command/idempotence.py
  src/molecule/command/prepare.py
  src/molecule/command/side_effect.py
  src/molecule/command/syntax.py
  src/molecule/command/test.py
  src/molecule/command/verify.py
  src/molecule/config.py
  src/molecule/scenario.py
  src/molecule/types.py
  tests/unit/provisioner/test_ansible.py
Labels: enhancement

#4451 Strip argument documentation from command help text.
  src/molecule/command/check.py
  src/molecule/command/cleanup.py
  src/molecule/command/converge.py
  src/molecule/command/create.py
  src/molecule/command/dependency.py
  src/molecule/command/destroy.py
  src/molecule/command/drivers.py
  src/molecule/command/idempotence.py
  src/molecule/command/init/scenario.py
  src/molecule/command/list.py
  src/molecule/command/login.py
  src/molecule/command/matrix.py
  src/molecule/command/prepare.py
  src/molecule/command/reset.py
  src/molecule/command/side_effect.py
  src/molecule/command/syntax.py
  src/molecule/command/test.py
  src/molecule/command/verify.py
  src/molecule/shell.py
Labels: bug
